/* DragDropAction.c generated by valac 0.30.1, the Vala compiler
 * generated from DragDropAction.vala, do not modify */

/**/
/*  Copyright (C) 2013 Tom Beckmann*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <clutter/clutter.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gee.h>


#define GALA_TYPE_DRAG_DROP_ACTION_TYPE (gala_drag_drop_action_type_get_type ())

#define GALA_TYPE_DRAG_DROP_ACTION (gala_drag_drop_action_get_type ())
#define GALA_DRAG_DROP_ACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GALA_TYPE_DRAG_DROP_ACTION, GalaDragDropAction))
#define GALA_DRAG_DROP_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GALA_TYPE_DRAG_DROP_ACTION, GalaDragDropActionClass))
#define GALA_IS_DRAG_DROP_ACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GALA_TYPE_DRAG_DROP_ACTION))
#define GALA_IS_DRAG_DROP_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GALA_TYPE_DRAG_DROP_ACTION))
#define GALA_DRAG_DROP_ACTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GALA_TYPE_DRAG_DROP_ACTION, GalaDragDropActionClass))

typedef struct _GalaDragDropAction GalaDragDropAction;
typedef struct _GalaDragDropActionClass GalaDragDropActionClass;
typedef struct _GalaDragDropActionPrivate GalaDragDropActionPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))

typedef enum  {
	GALA_DRAG_DROP_ACTION_TYPE_SOURCE = 0,
	GALA_DRAG_DROP_ACTION_TYPE_DESTINATION
} GalaDragDropActionType;

struct _GalaDragDropAction {
	ClutterAction parent_instance;
	GalaDragDropActionPrivate * priv;
};

struct _GalaDragDropActionClass {
	ClutterActionClass parent_class;
};

struct _GalaDragDropActionPrivate {
	GalaDragDropActionType _drag_type;
	gchar* _drag_id;
	ClutterActor* _handle;
	gboolean _dragging;
	gboolean _allow_bubbling;
	ClutterActor* hovered;
	gboolean clicked;
	gfloat last_x;
	gfloat last_y;
};


static gpointer gala_drag_drop_action_parent_class = NULL;
static GeeHashMap* gala_drag_drop_action_sources;
static GeeHashMap* gala_drag_drop_action_sources = NULL;

GType gala_drag_drop_action_type_get_type (void) G_GNUC_CONST;
GType gala_drag_drop_action_get_type (void) G_GNUC_CONST;
#define GALA_DRAG_DROP_ACTION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GALA_TYPE_DRAG_DROP_ACTION, GalaDragDropActionPrivate))
enum  {
	GALA_DRAG_DROP_ACTION_DUMMY_PROPERTY,
	GALA_DRAG_DROP_ACTION_DRAG_TYPE,
	GALA_DRAG_DROP_ACTION_DRAG_ID,
	GALA_DRAG_DROP_ACTION_HANDLE,
	GALA_DRAG_DROP_ACTION_DRAGGING,
	GALA_DRAG_DROP_ACTION_ALLOW_BUBBLING
};
static void gala_drag_drop_action_release_actor (GalaDragDropAction* self, ClutterActor* actor);
GalaDragDropAction* gala_drag_drop_action_new (GalaDragDropActionType type, const gchar* id);
GalaDragDropAction* gala_drag_drop_action_construct (GType object_type, GalaDragDropActionType type, const gchar* id);
static void gala_drag_drop_action_real_set_actor (ClutterActorMeta* base, ClutterActor* new_actor);
static void gala_drag_drop_action_connect_actor (GalaDragDropAction* self, ClutterActor* actor);
GalaDragDropActionType gala_drag_drop_action_get_drag_type (GalaDragDropAction* self);
static gboolean gala_drag_drop_action_source_clicked (GalaDragDropAction* self, ClutterButtonEvent* event);
static gboolean _gala_drag_drop_action_source_clicked_clutter_actor_button_press_event (ClutterActor* _sender, ClutterButtonEvent* event, gpointer self);
const gchar* gala_drag_drop_action_get_drag_id (GalaDragDropAction* self);
static void gala_drag_drop_action_emit_crossed (GalaDragDropAction* self, ClutterActor* destination, gboolean hovered);
static GalaDragDropAction* gala_drag_drop_action_get_drag_drop_action (GalaDragDropAction* self, ClutterActor* actor);
static gboolean gala_drag_drop_action_follow_move (GalaDragDropAction* self, ClutterEvent* event);
static gboolean _gala_drag_drop_action_follow_move_clutter_actor_captured_event (ClutterActor* _sender, ClutterEvent* event, gpointer self);
gboolean gala_drag_drop_action_get_dragging (GalaDragDropAction* self);
static void gala_drag_drop_action_set_handle (GalaDragDropAction* self, ClutterActor* value);
ClutterActor* gala_drag_drop_action_get_handle (GalaDragDropAction* self);
static void gala_drag_drop_action_set_dragging (GalaDragDropAction* self, gboolean value);
void gala_drag_drop_action_cancel (GalaDragDropAction* self);
gboolean gala_drag_drop_action_get_allow_bubbling (GalaDragDropAction* self);
static void gala_drag_drop_action_finish (GalaDragDropAction* self);
static void gala_drag_drop_action_cleanup (GalaDragDropAction* self);
void gala_drag_drop_action_cancel_all_by_id (const gchar* id);
static void gala_drag_drop_action_set_drag_type (GalaDragDropAction* self, GalaDragDropActionType value);
static void gala_drag_drop_action_set_drag_id (GalaDragDropAction* self, const gchar* value);
void gala_drag_drop_action_set_allow_bubbling (GalaDragDropAction* self, gboolean value);
static void g_cclosure_user_marshal_OBJECT__FLOAT_FLOAT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void g_cclosure_user_marshal_VOID__OBJECT_BOOLEAN (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void gala_drag_drop_action_finalize (GObject* obj);
static void _vala_gala_drag_drop_action_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_gala_drag_drop_action_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GType gala_drag_drop_action_type_get_type (void) {
	static volatile gsize gala_drag_drop_action_type_type_id__volatile = 0;
	if (g_once_init_enter (&gala_drag_drop_action_type_type_id__volatile)) {
		static const GEnumValue values[] = {{GALA_DRAG_DROP_ACTION_TYPE_SOURCE, "GALA_DRAG_DROP_ACTION_TYPE_SOURCE", "source"}, {GALA_DRAG_DROP_ACTION_TYPE_DESTINATION, "GALA_DRAG_DROP_ACTION_TYPE_DESTINATION", "destination"}, {0, NULL, NULL}};
		GType gala_drag_drop_action_type_type_id;
		gala_drag_drop_action_type_type_id = g_enum_register_static ("GalaDragDropActionType", values);
		g_once_init_leave (&gala_drag_drop_action_type_type_id__volatile, gala_drag_drop_action_type_type_id);
	}
	return gala_drag_drop_action_type_type_id__volatile;
}


/**
 * Create a new DragDropAction
 *
 * @param type The type of this actor
 * @param id   An ID that marks which sources can be dragged on
 *             which destinations. It has to be the same for all actors that
 *             should be compatible with each other.
 */
GalaDragDropAction* gala_drag_drop_action_construct (GType object_type, GalaDragDropActionType type, const gchar* id) {
	GalaDragDropAction * self = NULL;
	GalaDragDropActionType _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
#line 113 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_val_if_fail (id != NULL, NULL);
#line 115 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = type;
#line 115 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp1_ = id;
#line 115 "/home/nick/work/gala/src/DragDropAction.vala"
	self = (GalaDragDropAction*) g_object_new (object_type, "drag-type", _tmp0_, "drag-id", _tmp1_, NULL);
#line 117 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp2_ = gala_drag_drop_action_sources;
#line 117 "/home/nick/work/gala/src/DragDropAction.vala"
	if (_tmp2_ == NULL) {
#line 159 "DragDropAction.c"
		GeeHashMap* _tmp3_ = NULL;
#line 118 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp3_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, GEE_TYPE_LINKED_LIST, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 118 "/home/nick/work/gala/src/DragDropAction.vala"
		_g_object_unref0 (gala_drag_drop_action_sources);
#line 118 "/home/nick/work/gala/src/DragDropAction.vala"
		gala_drag_drop_action_sources = _tmp3_;
#line 167 "DragDropAction.c"
	}
#line 113 "/home/nick/work/gala/src/DragDropAction.vala"
	return self;
#line 171 "DragDropAction.c"
}


GalaDragDropAction* gala_drag_drop_action_new (GalaDragDropActionType type, const gchar* id) {
#line 113 "/home/nick/work/gala/src/DragDropAction.vala"
	return gala_drag_drop_action_construct (GALA_TYPE_DRAG_DROP_ACTION, type, id);
#line 178 "DragDropAction.c"
}


static void gala_drag_drop_action_real_set_actor (ClutterActorMeta* base, ClutterActor* new_actor) {
	GalaDragDropAction * self;
	ClutterActor* _tmp0_ = NULL;
	ClutterActor* _tmp1_ = NULL;
	ClutterActor* _tmp4_ = NULL;
	ClutterActor* _tmp6_ = NULL;
#line 127 "/home/nick/work/gala/src/DragDropAction.vala"
	self = (GalaDragDropAction*) base;
#line 129 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = clutter_actor_meta_get_actor ((ClutterActorMeta*) self);
#line 129 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp1_ = _tmp0_;
#line 129 "/home/nick/work/gala/src/DragDropAction.vala"
	if (_tmp1_ != NULL) {
#line 196 "DragDropAction.c"
		ClutterActor* _tmp2_ = NULL;
		ClutterActor* _tmp3_ = NULL;
#line 130 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp2_ = clutter_actor_meta_get_actor ((ClutterActorMeta*) self);
#line 130 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp3_ = _tmp2_;
#line 130 "/home/nick/work/gala/src/DragDropAction.vala"
		gala_drag_drop_action_release_actor (self, _tmp3_);
#line 205 "DragDropAction.c"
	}
#line 133 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp4_ = new_actor;
#line 133 "/home/nick/work/gala/src/DragDropAction.vala"
	if (_tmp4_ != NULL) {
#line 211 "DragDropAction.c"
		ClutterActor* _tmp5_ = NULL;
#line 134 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp5_ = new_actor;
#line 134 "/home/nick/work/gala/src/DragDropAction.vala"
		gala_drag_drop_action_connect_actor (self, _tmp5_);
#line 217 "DragDropAction.c"
	}
#line 137 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp6_ = new_actor;
#line 137 "/home/nick/work/gala/src/DragDropAction.vala"
	CLUTTER_ACTOR_META_CLASS (gala_drag_drop_action_parent_class)->set_actor ((ClutterActorMeta*) G_TYPE_CHECK_INSTANCE_CAST (self, clutter_action_get_type (), ClutterAction), _tmp6_);
#line 223 "DragDropAction.c"
}


static gboolean _gala_drag_drop_action_source_clicked_clutter_actor_button_press_event (ClutterActor* _sender, ClutterButtonEvent* event, gpointer self) {
	gboolean result;
	result = gala_drag_drop_action_source_clicked ((GalaDragDropAction*) self, event);
#line 143 "/home/nick/work/gala/src/DragDropAction.vala"
	return result;
#line 232 "DragDropAction.c"
}


static void gala_drag_drop_action_release_actor (GalaDragDropAction* self, ClutterActor* actor) {
	GalaDragDropActionType _tmp0_ = 0;
#line 140 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (self != NULL);
#line 140 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (actor != NULL);
#line 142 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = self->priv->_drag_type;
#line 142 "/home/nick/work/gala/src/DragDropAction.vala"
	if (_tmp0_ == GALA_DRAG_DROP_ACTION_TYPE_SOURCE) {
#line 246 "DragDropAction.c"
		ClutterActor* _tmp1_ = NULL;
		guint _tmp2_ = 0U;
		GeeLinkedList* source_list = NULL;
		GeeHashMap* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		gpointer _tmp5_ = NULL;
		GeeLinkedList* _tmp6_ = NULL;
		ClutterActor* _tmp7_ = NULL;
#line 143 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp1_ = actor;
#line 143 "/home/nick/work/gala/src/DragDropAction.vala"
		g_signal_parse_name ("button-press-event", clutter_actor_get_type (), &_tmp2_, NULL, FALSE);
#line 143 "/home/nick/work/gala/src/DragDropAction.vala"
		g_signal_handlers_disconnect_matched (_tmp1_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp2_, 0, NULL, (GCallback) _gala_drag_drop_action_source_clicked_clutter_actor_button_press_event, self);
#line 145 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp3_ = gala_drag_drop_action_sources;
#line 145 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp4_ = self->priv->_drag_id;
#line 145 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp5_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp3_, _tmp4_);
#line 145 "/home/nick/work/gala/src/DragDropAction.vala"
		source_list = (GeeLinkedList*) _tmp5_;
#line 146 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp6_ = source_list;
#line 146 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp7_ = actor;
#line 146 "/home/nick/work/gala/src/DragDropAction.vala"
		gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp6_, _tmp7_);
#line 142 "/home/nick/work/gala/src/DragDropAction.vala"
		_g_object_unref0 (source_list);
#line 277 "DragDropAction.c"
	}
}


static void gala_drag_drop_action_connect_actor (GalaDragDropAction* self, ClutterActor* actor) {
	GalaDragDropActionType _tmp0_ = 0;
#line 150 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (self != NULL);
#line 150 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (actor != NULL);
#line 152 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = self->priv->_drag_type;
#line 152 "/home/nick/work/gala/src/DragDropAction.vala"
	if (_tmp0_ == GALA_DRAG_DROP_ACTION_TYPE_SOURCE) {
#line 292 "DragDropAction.c"
		ClutterActor* _tmp1_ = NULL;
		GeeLinkedList* source_list = NULL;
		GeeHashMap* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		gpointer _tmp4_ = NULL;
		GeeLinkedList* _tmp5_ = NULL;
		GeeLinkedList* _tmp10_ = NULL;
		ClutterActor* _tmp11_ = NULL;
#line 153 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp1_ = actor;
#line 153 "/home/nick/work/gala/src/DragDropAction.vala"
		g_signal_connect_object (_tmp1_, "button-press-event", (GCallback) _gala_drag_drop_action_source_clicked_clutter_actor_button_press_event, self, 0);
#line 155 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp2_ = gala_drag_drop_action_sources;
#line 155 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp3_ = self->priv->_drag_id;
#line 155 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp4_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp2_, _tmp3_);
#line 155 "/home/nick/work/gala/src/DragDropAction.vala"
		source_list = (GeeLinkedList*) _tmp4_;
#line 156 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp5_ = source_list;
#line 156 "/home/nick/work/gala/src/DragDropAction.vala"
		if (_tmp5_ == NULL) {
#line 317 "DragDropAction.c"
			GeeLinkedList* _tmp6_ = NULL;
			GeeHashMap* _tmp7_ = NULL;
			const gchar* _tmp8_ = NULL;
			GeeLinkedList* _tmp9_ = NULL;
#line 157 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp6_ = gee_linked_list_new (clutter_actor_get_type (), (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
#line 157 "/home/nick/work/gala/src/DragDropAction.vala"
			_g_object_unref0 (source_list);
#line 157 "/home/nick/work/gala/src/DragDropAction.vala"
			source_list = _tmp6_;
#line 158 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp7_ = gala_drag_drop_action_sources;
#line 158 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp8_ = self->priv->_drag_id;
#line 158 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp9_ = source_list;
#line 158 "/home/nick/work/gala/src/DragDropAction.vala"
			gee_abstract_map_set ((GeeAbstractMap*) _tmp7_, _tmp8_, _tmp9_);
#line 336 "DragDropAction.c"
		}
#line 161 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp10_ = source_list;
#line 161 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp11_ = actor;
#line 161 "/home/nick/work/gala/src/DragDropAction.vala"
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp10_, _tmp11_);
#line 152 "/home/nick/work/gala/src/DragDropAction.vala"
		_g_object_unref0 (source_list);
#line 346 "DragDropAction.c"
	}
}


static void gala_drag_drop_action_emit_crossed (GalaDragDropAction* self, ClutterActor* destination, gboolean hovered) {
	ClutterActor* _tmp0_ = NULL;
	GalaDragDropAction* _tmp1_ = NULL;
	GalaDragDropAction* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	ClutterActor* _tmp4_ = NULL;
	gboolean _tmp5_ = FALSE;
#line 165 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (self != NULL);
#line 165 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (destination != NULL);
#line 167 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = destination;
#line 167 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp1_ = gala_drag_drop_action_get_drag_drop_action (self, _tmp0_);
#line 167 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp2_ = _tmp1_;
#line 167 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp3_ = hovered;
#line 167 "/home/nick/work/gala/src/DragDropAction.vala"
	g_signal_emit_by_name (_tmp2_, "crossed", _tmp3_);
#line 167 "/home/nick/work/gala/src/DragDropAction.vala"
	_g_object_unref0 (_tmp2_);
#line 168 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp4_ = destination;
#line 168 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp5_ = hovered;
#line 168 "/home/nick/work/gala/src/DragDropAction.vala"
	g_signal_emit_by_name (self, "destination-crossed", _tmp4_, _tmp5_);
#line 380 "DragDropAction.c"
}


static gboolean _gala_drag_drop_action_follow_move_clutter_actor_captured_event (ClutterActor* _sender, ClutterEvent* event, gpointer self) {
	gboolean result;
	result = gala_drag_drop_action_follow_move ((GalaDragDropAction*) self, event);
#line 178 "/home/nick/work/gala/src/DragDropAction.vala"
	return result;
#line 389 "DragDropAction.c"
}


static gboolean gala_drag_drop_action_source_clicked (GalaDragDropAction* self, ClutterButtonEvent* event) {
	gboolean result = FALSE;
	ClutterButtonEvent _tmp0_ = {0};
	guint32 _tmp1_ = 0U;
	ClutterActor* _tmp4_ = NULL;
	ClutterActor* _tmp5_ = NULL;
	ClutterStage* _tmp6_ = NULL;
	ClutterButtonEvent _tmp7_ = {0};
	gfloat _tmp8_ = 0.0F;
	ClutterButtonEvent _tmp9_ = {0};
	gfloat _tmp10_ = 0.0F;
#line 171 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 171 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 173 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = *event;
#line 173 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp1_ = _tmp0_.button;
#line 173 "/home/nick/work/gala/src/DragDropAction.vala"
	if (_tmp1_ != ((guint32) 1)) {
#line 414 "DragDropAction.c"
		ClutterButtonEvent _tmp2_ = {0};
		guint32 _tmp3_ = 0U;
#line 174 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp2_ = *event;
#line 174 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp3_ = _tmp2_.button;
#line 174 "/home/nick/work/gala/src/DragDropAction.vala"
		g_signal_emit_by_name (self, "actor-clicked", _tmp3_);
#line 175 "/home/nick/work/gala/src/DragDropAction.vala"
		result = FALSE;
#line 175 "/home/nick/work/gala/src/DragDropAction.vala"
		return result;
#line 427 "DragDropAction.c"
	}
#line 178 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp4_ = clutter_actor_meta_get_actor ((ClutterActorMeta*) self);
#line 178 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp5_ = _tmp4_;
#line 178 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp6_ = clutter_actor_get_stage (_tmp5_);
#line 178 "/home/nick/work/gala/src/DragDropAction.vala"
	g_signal_connect_object ((ClutterActor*) _tmp6_, "captured-event", (GCallback) _gala_drag_drop_action_follow_move_clutter_actor_captured_event, self, 0);
#line 179 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv->clicked = TRUE;
#line 180 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp7_ = *event;
#line 180 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp8_ = _tmp7_.x;
#line 180 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv->last_x = _tmp8_;
#line 181 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp9_ = *event;
#line 181 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp10_ = _tmp9_.y;
#line 181 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv->last_y = _tmp10_;
#line 183 "/home/nick/work/gala/src/DragDropAction.vala"
	result = TRUE;
#line 183 "/home/nick/work/gala/src/DragDropAction.vala"
	return result;
#line 455 "DragDropAction.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
	return self ? g_object_ref (self) : NULL;
#line 462 "DragDropAction.c"
}


static gboolean gala_drag_drop_action_follow_move (GalaDragDropAction* self, ClutterEvent* event) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	ClutterEvent* _tmp76_ = NULL;
	ClutterEventType _tmp77_ = 0;
#line 186 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 186 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 189 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = self->priv->_dragging;
#line 189 "/home/nick/work/gala/src/DragDropAction.vala"
	if (!_tmp0_) {
#line 479 "DragDropAction.c"
		ClutterEvent* _tmp1_ = NULL;
		ClutterEventType _tmp2_ = 0;
#line 190 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp1_ = event;
#line 190 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp2_ = clutter_event_type (_tmp1_);
#line 190 "/home/nick/work/gala/src/DragDropAction.vala"
		switch (_tmp2_) {
#line 190 "/home/nick/work/gala/src/DragDropAction.vala"
			case CLUTTER_MOTION:
#line 490 "DragDropAction.c"
			{
				gfloat x = 0.0F;
				gfloat y = 0.0F;
				ClutterEvent* _tmp3_ = NULL;
				gfloat _tmp4_ = 0.0F;
				gfloat _tmp5_ = 0.0F;
				gint drag_threshold = 0;
				ClutterSettings* _tmp6_ = NULL;
				gint _tmp7_ = 0;
				gint _tmp8_ = 0;
				gboolean _tmp9_ = FALSE;
				gfloat _tmp10_ = 0.0F;
				gfloat _tmp11_ = 0.0F;
				gfloat _tmp12_ = 0.0F;
				gint _tmp13_ = 0;
#line 193 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp3_ = event;
#line 193 "/home/nick/work/gala/src/DragDropAction.vala"
				clutter_event_get_coords (_tmp3_, &_tmp4_, &_tmp5_);
#line 193 "/home/nick/work/gala/src/DragDropAction.vala"
				x = _tmp4_;
#line 193 "/home/nick/work/gala/src/DragDropAction.vala"
				y = _tmp5_;
#line 195 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp6_ = clutter_settings_get_default ();
#line 195 "/home/nick/work/gala/src/DragDropAction.vala"
				g_object_get (_tmp6_, "dnd-drag-threshold", &_tmp7_, NULL);
#line 195 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp8_ = _tmp7_;
#line 195 "/home/nick/work/gala/src/DragDropAction.vala"
				drag_threshold = _tmp8_;
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp10_ = self->priv->last_x;
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp11_ = x;
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp12_ = fabsf (_tmp10_ - _tmp11_);
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp13_ = drag_threshold;
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
				if (_tmp12_ > ((gfloat) _tmp13_)) {
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp9_ = TRUE;
#line 534 "DragDropAction.c"
				} else {
					gfloat _tmp14_ = 0.0F;
					gfloat _tmp15_ = 0.0F;
					gfloat _tmp16_ = 0.0F;
					gint _tmp17_ = 0;
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp14_ = self->priv->last_y;
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp15_ = y;
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp16_ = fabsf (_tmp14_ - _tmp15_);
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp17_ = drag_threshold;
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp9_ = _tmp16_ > ((gfloat) _tmp17_);
#line 550 "DragDropAction.c"
				}
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
				if (_tmp9_) {
#line 554 "DragDropAction.c"
					gfloat _tmp18_ = 0.0F;
					gfloat _tmp19_ = 0.0F;
					ClutterActor* _tmp20_ = NULL;
					ClutterActor* _tmp21_ = NULL;
					ClutterActor* _tmp22_ = NULL;
					ClutterActor* _tmp27_ = NULL;
					GeeLinkedList* source_list = NULL;
					GeeHashMap* _tmp28_ = NULL;
					const gchar* _tmp29_ = NULL;
					gpointer _tmp30_ = NULL;
					GeeLinkedList* _tmp31_ = NULL;
#line 197 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp18_ = x;
#line 197 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp19_ = y;
#line 197 "/home/nick/work/gala/src/DragDropAction.vala"
					g_signal_emit_by_name (self, "drag-begin", _tmp18_, _tmp19_, &_tmp20_);
#line 197 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp21_ = _tmp20_;
#line 197 "/home/nick/work/gala/src/DragDropAction.vala"
					gala_drag_drop_action_set_handle (self, _tmp21_);
#line 197 "/home/nick/work/gala/src/DragDropAction.vala"
					_g_object_unref0 (_tmp21_);
#line 198 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp22_ = self->priv->_handle;
#line 198 "/home/nick/work/gala/src/DragDropAction.vala"
					if (_tmp22_ == NULL) {
#line 582 "DragDropAction.c"
						ClutterActor* _tmp23_ = NULL;
						ClutterActor* _tmp24_ = NULL;
						ClutterStage* _tmp25_ = NULL;
						guint _tmp26_ = 0U;
#line 199 "/home/nick/work/gala/src/DragDropAction.vala"
						_tmp23_ = clutter_actor_meta_get_actor ((ClutterActorMeta*) self);
#line 199 "/home/nick/work/gala/src/DragDropAction.vala"
						_tmp24_ = _tmp23_;
#line 199 "/home/nick/work/gala/src/DragDropAction.vala"
						_tmp25_ = clutter_actor_get_stage (_tmp24_);
#line 199 "/home/nick/work/gala/src/DragDropAction.vala"
						g_signal_parse_name ("captured-event", clutter_actor_get_type (), &_tmp26_, NULL, FALSE);
#line 199 "/home/nick/work/gala/src/DragDropAction.vala"
						g_signal_handlers_disconnect_matched ((ClutterActor*) _tmp25_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp26_, 0, NULL, (GCallback) _gala_drag_drop_action_follow_move_clutter_actor_captured_event, self);
#line 200 "/home/nick/work/gala/src/DragDropAction.vala"
						g_critical ("DragDropAction.vala:200: No handle has been returned by the started si" \
"gnal, aborting drag.");
#line 201 "/home/nick/work/gala/src/DragDropAction.vala"
						result = FALSE;
#line 201 "/home/nick/work/gala/src/DragDropAction.vala"
						return result;
#line 603 "DragDropAction.c"
					}
#line 204 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp27_ = self->priv->_handle;
#line 204 "/home/nick/work/gala/src/DragDropAction.vala"
					clutter_actor_set_reactive (_tmp27_, FALSE);
#line 206 "/home/nick/work/gala/src/DragDropAction.vala"
					self->priv->clicked = FALSE;
#line 207 "/home/nick/work/gala/src/DragDropAction.vala"
					gala_drag_drop_action_set_dragging (self, TRUE);
#line 209 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp28_ = gala_drag_drop_action_sources;
#line 209 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp29_ = self->priv->_drag_id;
#line 209 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp30_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp28_, _tmp29_);
#line 209 "/home/nick/work/gala/src/DragDropAction.vala"
					source_list = (GeeLinkedList*) _tmp30_;
#line 210 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp31_ = source_list;
#line 210 "/home/nick/work/gala/src/DragDropAction.vala"
					if (_tmp31_ != NULL) {
#line 625 "DragDropAction.c"
						{
							GeeLinkedList* _actor_list = NULL;
							GeeLinkedList* _tmp32_ = NULL;
							GeeLinkedList* _tmp33_ = NULL;
							gint _actor_size = 0;
							GeeLinkedList* _tmp34_ = NULL;
							gint _tmp35_ = 0;
							gint _tmp36_ = 0;
							gint _actor_index = 0;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
							_tmp32_ = source_list;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
							_tmp33_ = _g_object_ref0 (_tmp32_);
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
							_actor_list = _tmp33_;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
							_tmp34_ = _actor_list;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
							_tmp35_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp34_);
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
							_tmp36_ = _tmp35_;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
							_actor_size = _tmp36_;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
							_actor_index = -1;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
							while (TRUE) {
#line 653 "DragDropAction.c"
								gint _tmp37_ = 0;
								gint _tmp38_ = 0;
								gint _tmp39_ = 0;
								ClutterActor* actor = NULL;
								GeeLinkedList* _tmp40_ = NULL;
								gint _tmp41_ = 0;
								gpointer _tmp42_ = NULL;
								ClutterActor* _tmp43_ = NULL;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
								_tmp37_ = _actor_index;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
								_actor_index = _tmp37_ + 1;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
								_tmp38_ = _actor_index;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
								_tmp39_ = _actor_size;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
								if (!(_tmp38_ < _tmp39_)) {
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
									break;
#line 674 "DragDropAction.c"
								}
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
								_tmp40_ = _actor_list;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
								_tmp41_ = _actor_index;
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
								_tmp42_ = gee_abstract_list_get ((GeeAbstractList*) _tmp40_, _tmp41_);
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
								actor = (ClutterActor*) _tmp42_;
#line 212 "/home/nick/work/gala/src/DragDropAction.vala"
								_tmp43_ = actor;
#line 212 "/home/nick/work/gala/src/DragDropAction.vala"
								clutter_actor_set_reactive (_tmp43_, FALSE);
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
								_g_object_unref0 (actor);
#line 690 "DragDropAction.c"
							}
#line 211 "/home/nick/work/gala/src/DragDropAction.vala"
							_g_object_unref0 (_actor_list);
#line 694 "DragDropAction.c"
						}
					}
#line 196 "/home/nick/work/gala/src/DragDropAction.vala"
					_g_object_unref0 (source_list);
#line 699 "DragDropAction.c"
				}
#line 216 "/home/nick/work/gala/src/DragDropAction.vala"
				result = TRUE;
#line 216 "/home/nick/work/gala/src/DragDropAction.vala"
				return result;
#line 705 "DragDropAction.c"
			}
#line 190 "/home/nick/work/gala/src/DragDropAction.vala"
			case CLUTTER_BUTTON_RELEASE:
#line 709 "DragDropAction.c"
			{
				gfloat x = 0.0F;
				gfloat y = 0.0F;
				gfloat ex = 0.0F;
				gfloat ey = 0.0F;
				ClutterEvent* _tmp44_ = NULL;
				gfloat _tmp45_ = 0.0F;
				gfloat _tmp46_ = 0.0F;
				ClutterActor* _tmp47_ = NULL;
				ClutterActor* _tmp48_ = NULL;
				gfloat _tmp49_ = 0.0F;
				gfloat _tmp50_ = 0.0F;
				gboolean _tmp51_ = FALSE;
				gboolean _tmp52_ = FALSE;
				gboolean _tmp53_ = FALSE;
				gfloat _tmp54_ = 0.0F;
				gfloat _tmp55_ = 0.0F;
				ClutterActor* _tmp72_ = NULL;
				ClutterActor* _tmp73_ = NULL;
				ClutterStage* _tmp74_ = NULL;
				guint _tmp75_ = 0U;
#line 219 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp44_ = event;
#line 219 "/home/nick/work/gala/src/DragDropAction.vala"
				clutter_event_get_coords (_tmp44_, &_tmp45_, &_tmp46_);
#line 219 "/home/nick/work/gala/src/DragDropAction.vala"
				ex = _tmp45_;
#line 219 "/home/nick/work/gala/src/DragDropAction.vala"
				ey = _tmp46_;
#line 220 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp47_ = clutter_actor_meta_get_actor ((ClutterActorMeta*) self);
#line 220 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp48_ = _tmp47_;
#line 220 "/home/nick/work/gala/src/DragDropAction.vala"
				clutter_actor_get_transformed_position (_tmp48_, &_tmp49_, &_tmp50_);
#line 220 "/home/nick/work/gala/src/DragDropAction.vala"
				x = _tmp49_;
#line 220 "/home/nick/work/gala/src/DragDropAction.vala"
				y = _tmp50_;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp54_ = x;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp55_ = ex;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
				if (_tmp54_ < _tmp55_) {
#line 755 "DragDropAction.c"
					gfloat _tmp56_ = 0.0F;
					ClutterActor* _tmp57_ = NULL;
					ClutterActor* _tmp58_ = NULL;
					gfloat _tmp59_ = 0.0F;
					gfloat _tmp60_ = 0.0F;
					gfloat _tmp61_ = 0.0F;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp56_ = x;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp57_ = clutter_actor_meta_get_actor ((ClutterActorMeta*) self);
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp58_ = _tmp57_;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp59_ = clutter_actor_get_width (_tmp58_);
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp60_ = _tmp59_;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp61_ = ex;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp53_ = (_tmp56_ + _tmp60_) > _tmp61_;
#line 776 "DragDropAction.c"
				} else {
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp53_ = FALSE;
#line 780 "DragDropAction.c"
				}
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
				if (_tmp53_) {
#line 784 "DragDropAction.c"
					gfloat _tmp62_ = 0.0F;
					gfloat _tmp63_ = 0.0F;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp62_ = y;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp63_ = ey;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp52_ = _tmp62_ < _tmp63_;
#line 793 "DragDropAction.c"
				} else {
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp52_ = FALSE;
#line 797 "DragDropAction.c"
				}
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
				if (_tmp52_) {
#line 801 "DragDropAction.c"
					gfloat _tmp64_ = 0.0F;
					ClutterActor* _tmp65_ = NULL;
					ClutterActor* _tmp66_ = NULL;
					gfloat _tmp67_ = 0.0F;
					gfloat _tmp68_ = 0.0F;
					gfloat _tmp69_ = 0.0F;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp64_ = y;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp65_ = clutter_actor_meta_get_actor ((ClutterActorMeta*) self);
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp66_ = _tmp65_;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp67_ = clutter_actor_get_height (_tmp66_);
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp68_ = _tmp67_;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp69_ = ey;
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp51_ = (_tmp64_ + _tmp68_) > _tmp69_;
#line 822 "DragDropAction.c"
				} else {
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp51_ = FALSE;
#line 826 "DragDropAction.c"
				}
#line 223 "/home/nick/work/gala/src/DragDropAction.vala"
				if (_tmp51_) {
#line 830 "DragDropAction.c"
					ClutterEvent* _tmp70_ = NULL;
					guint32 _tmp71_ = 0U;
#line 224 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp70_ = event;
#line 224 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp71_ = clutter_event_get_button (_tmp70_);
#line 224 "/home/nick/work/gala/src/DragDropAction.vala"
					g_signal_emit_by_name (self, "actor-clicked", _tmp71_);
#line 839 "DragDropAction.c"
				}
#line 227 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp72_ = clutter_actor_meta_get_actor ((ClutterActorMeta*) self);
#line 227 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp73_ = _tmp72_;
#line 227 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp74_ = clutter_actor_get_stage (_tmp73_);
#line 227 "/home/nick/work/gala/src/DragDropAction.vala"
				g_signal_parse_name ("captured-event", clutter_actor_get_type (), &_tmp75_, NULL, FALSE);
#line 227 "/home/nick/work/gala/src/DragDropAction.vala"
				g_signal_handlers_disconnect_matched ((ClutterActor*) _tmp74_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp75_, 0, NULL, (GCallback) _gala_drag_drop_action_follow_move_clutter_actor_captured_event, self);
#line 228 "/home/nick/work/gala/src/DragDropAction.vala"
				self->priv->clicked = FALSE;
#line 229 "/home/nick/work/gala/src/DragDropAction.vala"
				gala_drag_drop_action_set_dragging (self, FALSE);
#line 230 "/home/nick/work/gala/src/DragDropAction.vala"
				result = TRUE;
#line 230 "/home/nick/work/gala/src/DragDropAction.vala"
				return result;
#line 859 "DragDropAction.c"
			}
			default:
			{
#line 232 "/home/nick/work/gala/src/DragDropAction.vala"
				result = TRUE;
#line 232 "/home/nick/work/gala/src/DragDropAction.vala"
				return result;
#line 867 "DragDropAction.c"
			}
		}
	}
#line 236 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp76_ = event;
#line 236 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp77_ = clutter_event_type (_tmp76_);
#line 236 "/home/nick/work/gala/src/DragDropAction.vala"
	switch (_tmp77_) {
#line 236 "/home/nick/work/gala/src/DragDropAction.vala"
		case CLUTTER_KEY_PRESS:
#line 879 "DragDropAction.c"
		{
			ClutterEvent* _tmp78_ = NULL;
			guint16 _tmp79_ = 0U;
#line 238 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp78_ = event;
#line 238 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp79_ = clutter_event_get_key_code (_tmp78_);
#line 238 "/home/nick/work/gala/src/DragDropAction.vala"
			if (((gint) _tmp79_) == CLUTTER_KEY_Escape) {
#line 239 "/home/nick/work/gala/src/DragDropAction.vala"
				gala_drag_drop_action_cancel (self);
#line 891 "DragDropAction.c"
			}
#line 241 "/home/nick/work/gala/src/DragDropAction.vala"
			result = TRUE;
#line 241 "/home/nick/work/gala/src/DragDropAction.vala"
			return result;
#line 897 "DragDropAction.c"
		}
#line 236 "/home/nick/work/gala/src/DragDropAction.vala"
		case CLUTTER_MOTION:
#line 901 "DragDropAction.c"
		{
			gfloat x = 0.0F;
			gfloat y = 0.0F;
			ClutterEvent* _tmp80_ = NULL;
			gfloat _tmp81_ = 0.0F;
			gfloat _tmp82_ = 0.0F;
			ClutterActor* _tmp83_ = NULL;
			ClutterActor* _tmp84_ = NULL;
			gfloat _tmp85_ = 0.0F;
			gfloat _tmp86_ = 0.0F;
			gfloat _tmp87_ = 0.0F;
			gfloat _tmp88_ = 0.0F;
			ClutterActor* _tmp89_ = NULL;
			ClutterActor* _tmp90_ = NULL;
			gfloat _tmp91_ = 0.0F;
			gfloat _tmp92_ = 0.0F;
			gfloat _tmp93_ = 0.0F;
			gfloat _tmp94_ = 0.0F;
			gfloat _tmp95_ = 0.0F;
			gfloat _tmp96_ = 0.0F;
			ClutterStage* stage = NULL;
			ClutterActor* _tmp97_ = NULL;
			ClutterActor* _tmp98_ = NULL;
			ClutterStage* _tmp99_ = NULL;
			ClutterStage* _tmp100_ = NULL;
			ClutterActor* actor = NULL;
			ClutterStage* _tmp101_ = NULL;
			gfloat _tmp102_ = 0.0F;
			gfloat _tmp103_ = 0.0F;
			ClutterActor* _tmp104_ = NULL;
			ClutterActor* _tmp105_ = NULL;
			GalaDragDropAction* action = NULL;
			gboolean _tmp106_ = FALSE;
			gboolean _tmp107_ = FALSE;
			ClutterActor* _tmp108_ = NULL;
			ClutterActor* _tmp121_ = NULL;
			ClutterActor* _tmp122_ = NULL;
			GalaDragDropAction* _tmp123_ = NULL;
			ClutterActor* _tmp126_ = NULL;
			ClutterActor* _tmp128_ = NULL;
			ClutterActor* _tmp129_ = NULL;
			ClutterActor* _tmp130_ = NULL;
#line 244 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp80_ = event;
#line 244 "/home/nick/work/gala/src/DragDropAction.vala"
			clutter_event_get_coords (_tmp80_, &_tmp81_, &_tmp82_);
#line 244 "/home/nick/work/gala/src/DragDropAction.vala"
			x = _tmp81_;
#line 244 "/home/nick/work/gala/src/DragDropAction.vala"
			y = _tmp82_;
#line 245 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp83_ = self->priv->_handle;
#line 245 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp84_ = self->priv->_handle;
#line 245 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp85_ = clutter_actor_get_x (_tmp84_);
#line 245 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp86_ = _tmp85_;
#line 245 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp87_ = self->priv->last_x;
#line 245 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp88_ = x;
#line 245 "/home/nick/work/gala/src/DragDropAction.vala"
			clutter_actor_set_x (_tmp84_, _tmp86_ - (_tmp87_ - _tmp88_));
#line 246 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp89_ = self->priv->_handle;
#line 246 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp90_ = self->priv->_handle;
#line 246 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp91_ = clutter_actor_get_y (_tmp90_);
#line 246 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp92_ = _tmp91_;
#line 246 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp93_ = self->priv->last_y;
#line 246 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp94_ = y;
#line 246 "/home/nick/work/gala/src/DragDropAction.vala"
			clutter_actor_set_y (_tmp90_, _tmp92_ - (_tmp93_ - _tmp94_));
#line 247 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp95_ = x;
#line 247 "/home/nick/work/gala/src/DragDropAction.vala"
			self->priv->last_x = _tmp95_;
#line 248 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp96_ = y;
#line 248 "/home/nick/work/gala/src/DragDropAction.vala"
			self->priv->last_y = _tmp96_;
#line 250 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp97_ = clutter_actor_meta_get_actor ((ClutterActorMeta*) self);
#line 250 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp98_ = _tmp97_;
#line 250 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp99_ = clutter_actor_get_stage (_tmp98_);
#line 250 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp100_ = _g_object_ref0 (_tmp99_);
#line 250 "/home/nick/work/gala/src/DragDropAction.vala"
			stage = _tmp100_;
#line 251 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp101_ = stage;
#line 251 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp102_ = x;
#line 251 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp103_ = y;
#line 251 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp104_ = clutter_stage_get_actor_at_pos (_tmp101_, CLUTTER_PICK_REACTIVE, (gint) _tmp102_, (gint) _tmp103_);
#line 251 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp105_ = _g_object_ref0 (_tmp104_);
#line 251 "/home/nick/work/gala/src/DragDropAction.vala"
			actor = _tmp105_;
#line 252 "/home/nick/work/gala/src/DragDropAction.vala"
			action = NULL;
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp108_ = actor;
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
			if (_tmp108_ != NULL) {
#line 1016 "DragDropAction.c"
				ClutterActor* _tmp109_ = NULL;
				GalaDragDropAction* _tmp110_ = NULL;
				GalaDragDropAction* _tmp111_ = NULL;
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp109_ = actor;
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp110_ = gala_drag_drop_action_get_drag_drop_action (self, _tmp109_);
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
				_g_object_unref0 (action);
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
				action = _tmp110_;
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp111_ = action;
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp107_ = _tmp111_ == NULL;
#line 1032 "DragDropAction.c"
			} else {
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp107_ = FALSE;
#line 1036 "DragDropAction.c"
			}
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
			if (_tmp107_) {
#line 1040 "DragDropAction.c"
				gboolean _tmp112_ = FALSE;
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp112_ = self->priv->_allow_bubbling;
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp106_ = _tmp112_;
#line 1046 "DragDropAction.c"
			} else {
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp106_ = FALSE;
#line 1050 "DragDropAction.c"
			}
#line 254 "/home/nick/work/gala/src/DragDropAction.vala"
			if (_tmp106_) {
#line 255 "/home/nick/work/gala/src/DragDropAction.vala"
				while (TRUE) {
#line 1056 "DragDropAction.c"
					ClutterActor* _tmp113_ = NULL;
					ClutterActor* _tmp114_ = NULL;
					ClutterActor* _tmp115_ = NULL;
					ClutterActor* _tmp116_ = NULL;
					ClutterStage* _tmp117_ = NULL;
					ClutterActor* _tmp118_ = NULL;
					GalaDragDropAction* _tmp119_ = NULL;
					GalaDragDropAction* _tmp120_ = NULL;
#line 255 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp113_ = actor;
#line 255 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp114_ = clutter_actor_get_parent (_tmp113_);
#line 255 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp115_ = _g_object_ref0 (_tmp114_);
#line 255 "/home/nick/work/gala/src/DragDropAction.vala"
					_g_object_unref0 (actor);
#line 255 "/home/nick/work/gala/src/DragDropAction.vala"
					actor = _tmp115_;
#line 255 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp116_ = actor;
#line 255 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp117_ = stage;
#line 255 "/home/nick/work/gala/src/DragDropAction.vala"
					if (!(_tmp116_ != G_TYPE_CHECK_INSTANCE_CAST (_tmp117_, clutter_actor_get_type (), ClutterActor))) {
#line 255 "/home/nick/work/gala/src/DragDropAction.vala"
						break;
#line 1083 "DragDropAction.c"
					}
#line 256 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp118_ = actor;
#line 256 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp119_ = gala_drag_drop_action_get_drag_drop_action (self, _tmp118_);
#line 256 "/home/nick/work/gala/src/DragDropAction.vala"
					_g_object_unref0 (action);
#line 256 "/home/nick/work/gala/src/DragDropAction.vala"
					action = _tmp119_;
#line 256 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp120_ = action;
#line 256 "/home/nick/work/gala/src/DragDropAction.vala"
					if (_tmp120_ != NULL) {
#line 257 "/home/nick/work/gala/src/DragDropAction.vala"
						break;
#line 1099 "DragDropAction.c"
					}
				}
			}
#line 262 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp121_ = actor;
#line 262 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp122_ = self->priv->hovered;
#line 262 "/home/nick/work/gala/src/DragDropAction.vala"
			if (_tmp121_ == _tmp122_) {
#line 263 "/home/nick/work/gala/src/DragDropAction.vala"
				result = TRUE;
#line 263 "/home/nick/work/gala/src/DragDropAction.vala"
				_g_object_unref0 (action);
#line 263 "/home/nick/work/gala/src/DragDropAction.vala"
				_g_object_unref0 (actor);
#line 263 "/home/nick/work/gala/src/DragDropAction.vala"
				_g_object_unref0 (stage);
#line 263 "/home/nick/work/gala/src/DragDropAction.vala"
				return result;
#line 1119 "DragDropAction.c"
			}
#line 265 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp123_ = action;
#line 265 "/home/nick/work/gala/src/DragDropAction.vala"
			if (_tmp123_ == NULL) {
#line 1125 "DragDropAction.c"
				ClutterActor* _tmp124_ = NULL;
#line 267 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp124_ = self->priv->hovered;
#line 267 "/home/nick/work/gala/src/DragDropAction.vala"
				if (_tmp124_ != NULL) {
#line 1131 "DragDropAction.c"
					ClutterActor* _tmp125_ = NULL;
#line 268 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp125_ = self->priv->hovered;
#line 268 "/home/nick/work/gala/src/DragDropAction.vala"
					gala_drag_drop_action_emit_crossed (self, _tmp125_, FALSE);
#line 269 "/home/nick/work/gala/src/DragDropAction.vala"
					_g_object_unref0 (self->priv->hovered);
#line 269 "/home/nick/work/gala/src/DragDropAction.vala"
					self->priv->hovered = NULL;
#line 1141 "DragDropAction.c"
				}
#line 272 "/home/nick/work/gala/src/DragDropAction.vala"
				result = TRUE;
#line 272 "/home/nick/work/gala/src/DragDropAction.vala"
				_g_object_unref0 (action);
#line 272 "/home/nick/work/gala/src/DragDropAction.vala"
				_g_object_unref0 (actor);
#line 272 "/home/nick/work/gala/src/DragDropAction.vala"
				_g_object_unref0 (stage);
#line 272 "/home/nick/work/gala/src/DragDropAction.vala"
				return result;
#line 1153 "DragDropAction.c"
			}
#line 276 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp126_ = self->priv->hovered;
#line 276 "/home/nick/work/gala/src/DragDropAction.vala"
			if (_tmp126_ != NULL) {
#line 1159 "DragDropAction.c"
				ClutterActor* _tmp127_ = NULL;
#line 277 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp127_ = self->priv->hovered;
#line 277 "/home/nick/work/gala/src/DragDropAction.vala"
				gala_drag_drop_action_emit_crossed (self, _tmp127_, FALSE);
#line 1165 "DragDropAction.c"
			}
#line 281 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp128_ = actor;
#line 281 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp129_ = _g_object_ref0 (_tmp128_);
#line 281 "/home/nick/work/gala/src/DragDropAction.vala"
			_g_object_unref0 (self->priv->hovered);
#line 281 "/home/nick/work/gala/src/DragDropAction.vala"
			self->priv->hovered = _tmp129_;
#line 282 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp130_ = self->priv->hovered;
#line 282 "/home/nick/work/gala/src/DragDropAction.vala"
			gala_drag_drop_action_emit_crossed (self, _tmp130_, TRUE);
#line 284 "/home/nick/work/gala/src/DragDropAction.vala"
			result = TRUE;
#line 284 "/home/nick/work/gala/src/DragDropAction.vala"
			_g_object_unref0 (action);
#line 284 "/home/nick/work/gala/src/DragDropAction.vala"
			_g_object_unref0 (actor);
#line 284 "/home/nick/work/gala/src/DragDropAction.vala"
			_g_object_unref0 (stage);
#line 284 "/home/nick/work/gala/src/DragDropAction.vala"
			return result;
#line 1189 "DragDropAction.c"
		}
#line 236 "/home/nick/work/gala/src/DragDropAction.vala"
		case CLUTTER_BUTTON_RELEASE:
#line 1193 "DragDropAction.c"
		{
			ClutterActor* _tmp131_ = NULL;
#line 286 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp131_ = self->priv->hovered;
#line 286 "/home/nick/work/gala/src/DragDropAction.vala"
			if (_tmp131_ != NULL) {
#line 287 "/home/nick/work/gala/src/DragDropAction.vala"
				gala_drag_drop_action_finish (self);
#line 1202 "DragDropAction.c"
			} else {
#line 289 "/home/nick/work/gala/src/DragDropAction.vala"
				gala_drag_drop_action_cancel (self);
#line 1206 "DragDropAction.c"
			}
#line 291 "/home/nick/work/gala/src/DragDropAction.vala"
			result = TRUE;
#line 291 "/home/nick/work/gala/src/DragDropAction.vala"
			return result;
#line 1212 "DragDropAction.c"
		}
#line 236 "/home/nick/work/gala/src/DragDropAction.vala"
		case CLUTTER_ENTER:
#line 236 "/home/nick/work/gala/src/DragDropAction.vala"
		case CLUTTER_LEAVE:
#line 1218 "DragDropAction.c"
		{
#line 294 "/home/nick/work/gala/src/DragDropAction.vala"
			result = TRUE;
#line 294 "/home/nick/work/gala/src/DragDropAction.vala"
			return result;
#line 1224 "DragDropAction.c"
		}
		default:
#line 236 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 1229 "DragDropAction.c"
	}
#line 297 "/home/nick/work/gala/src/DragDropAction.vala"
	result = FALSE;
#line 297 "/home/nick/work/gala/src/DragDropAction.vala"
	return result;
#line 1235 "DragDropAction.c"
}


/**
 * Looks for a DragDropAction instance if this actor has one or NULL.
 * It also checks if it is a DESTINATION and if the id matches
 *
 * @return the DragDropAction instance on this actor or NULL
 */
static GalaDragDropAction* gala_drag_drop_action_get_drag_drop_action (GalaDragDropAction* self, ClutterActor* actor) {
	GalaDragDropAction* result = NULL;
	GalaDragDropAction* drop_action = NULL;
	ClutterActor* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
#line 306 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 306 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_val_if_fail (actor != NULL, NULL);
#line 308 "/home/nick/work/gala/src/DragDropAction.vala"
	drop_action = NULL;
#line 310 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = actor;
#line 310 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp1_ = clutter_actor_get_actions (_tmp0_);
#line 1260 "DragDropAction.c"
	{
		GList* action_collection = NULL;
		GList* action_it = NULL;
#line 310 "/home/nick/work/gala/src/DragDropAction.vala"
		action_collection = _tmp1_;
#line 310 "/home/nick/work/gala/src/DragDropAction.vala"
		for (action_it = action_collection; action_it != NULL; action_it = action_it->next) {
#line 1268 "DragDropAction.c"
			ClutterAction* action = NULL;
#line 310 "/home/nick/work/gala/src/DragDropAction.vala"
			action = (ClutterAction*) action_it->data;
#line 1272 "DragDropAction.c"
			{
				ClutterAction* _tmp2_ = NULL;
				GalaDragDropAction* _tmp3_ = NULL;
				gboolean _tmp4_ = FALSE;
				gboolean _tmp5_ = FALSE;
				GalaDragDropAction* _tmp6_ = NULL;
#line 311 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp2_ = action;
#line 311 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, GALA_TYPE_DRAG_DROP_ACTION) ? ((GalaDragDropAction*) _tmp2_) : NULL);
#line 311 "/home/nick/work/gala/src/DragDropAction.vala"
				_g_object_unref0 (drop_action);
#line 311 "/home/nick/work/gala/src/DragDropAction.vala"
				drop_action = _tmp3_;
#line 312 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp6_ = drop_action;
#line 312 "/home/nick/work/gala/src/DragDropAction.vala"
				if (_tmp6_ == NULL) {
#line 312 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp5_ = TRUE;
#line 1293 "DragDropAction.c"
				} else {
					GalaDragDropAction* _tmp7_ = NULL;
					GalaDragDropActionType _tmp8_ = 0;
#line 313 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp7_ = drop_action;
#line 313 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp8_ = _tmp7_->priv->_drag_type;
#line 313 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp5_ = _tmp8_ != GALA_DRAG_DROP_ACTION_TYPE_DESTINATION;
#line 1303 "DragDropAction.c"
				}
#line 312 "/home/nick/work/gala/src/DragDropAction.vala"
				if (_tmp5_) {
#line 312 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp4_ = TRUE;
#line 1309 "DragDropAction.c"
				} else {
					GalaDragDropAction* _tmp9_ = NULL;
					const gchar* _tmp10_ = NULL;
					const gchar* _tmp11_ = NULL;
#line 314 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp9_ = drop_action;
#line 314 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp10_ = _tmp9_->priv->_drag_id;
#line 314 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp11_ = self->priv->_drag_id;
#line 314 "/home/nick/work/gala/src/DragDropAction.vala"
					_tmp4_ = g_strcmp0 (_tmp10_, _tmp11_) != 0;
#line 1322 "DragDropAction.c"
				}
#line 312 "/home/nick/work/gala/src/DragDropAction.vala"
				if (_tmp4_) {
#line 315 "/home/nick/work/gala/src/DragDropAction.vala"
					continue;
#line 1328 "DragDropAction.c"
				}
#line 317 "/home/nick/work/gala/src/DragDropAction.vala"
				result = drop_action;
#line 317 "/home/nick/work/gala/src/DragDropAction.vala"
				_g_list_free0 (action_collection);
#line 317 "/home/nick/work/gala/src/DragDropAction.vala"
				return result;
#line 1336 "DragDropAction.c"
			}
		}
#line 310 "/home/nick/work/gala/src/DragDropAction.vala"
		_g_list_free0 (action_collection);
#line 1341 "DragDropAction.c"
	}
#line 320 "/home/nick/work/gala/src/DragDropAction.vala"
	result = NULL;
#line 320 "/home/nick/work/gala/src/DragDropAction.vala"
	_g_object_unref0 (drop_action);
#line 320 "/home/nick/work/gala/src/DragDropAction.vala"
	return result;
#line 1349 "DragDropAction.c"
}


/**
 * Abort the drag
 */
void gala_drag_drop_action_cancel (GalaDragDropAction* self) {
#line 326 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (self != NULL);
#line 328 "/home/nick/work/gala/src/DragDropAction.vala"
	gala_drag_drop_action_cleanup (self);
#line 330 "/home/nick/work/gala/src/DragDropAction.vala"
	g_signal_emit_by_name (self, "drag-canceled");
#line 1363 "DragDropAction.c"
}


/**
 * Allows you to abort all drags currently running for a given drag-id
 */
void gala_drag_drop_action_cancel_all_by_id (const gchar* id) {
	GeeLinkedList* actors = NULL;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	GeeLinkedList* _tmp3_ = NULL;
#line 336 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (id != NULL);
#line 338 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = gala_drag_drop_action_sources;
#line 338 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp1_ = id;
#line 338 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp1_);
#line 338 "/home/nick/work/gala/src/DragDropAction.vala"
	actors = (GeeLinkedList*) _tmp2_;
#line 339 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp3_ = actors;
#line 339 "/home/nick/work/gala/src/DragDropAction.vala"
	if (_tmp3_ == NULL) {
#line 340 "/home/nick/work/gala/src/DragDropAction.vala"
		_g_object_unref0 (actors);
#line 340 "/home/nick/work/gala/src/DragDropAction.vala"
		return;
#line 1394 "DragDropAction.c"
	}
	{
		GeeLinkedList* _actor_list = NULL;
		GeeLinkedList* _tmp4_ = NULL;
		GeeLinkedList* _tmp5_ = NULL;
		gint _actor_size = 0;
		GeeLinkedList* _tmp6_ = NULL;
		gint _tmp7_ = 0;
		gint _tmp8_ = 0;
		gint _actor_index = 0;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp4_ = actors;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp5_ = _g_object_ref0 (_tmp4_);
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
		_actor_list = _tmp5_;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp6_ = _actor_list;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp7_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp6_);
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp8_ = _tmp7_;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
		_actor_size = _tmp8_;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
		_actor_index = -1;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
		while (TRUE) {
#line 1423 "DragDropAction.c"
			gint _tmp9_ = 0;
			gint _tmp10_ = 0;
			gint _tmp11_ = 0;
			ClutterActor* actor = NULL;
			GeeLinkedList* _tmp12_ = NULL;
			gint _tmp13_ = 0;
			gpointer _tmp14_ = NULL;
			ClutterActor* _tmp15_ = NULL;
			GList* _tmp16_ = NULL;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp9_ = _actor_index;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
			_actor_index = _tmp9_ + 1;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp10_ = _actor_index;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp11_ = _actor_size;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
			if (!(_tmp10_ < _tmp11_)) {
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
				break;
#line 1445 "DragDropAction.c"
			}
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp12_ = _actor_list;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp13_ = _actor_index;
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp14_ = gee_abstract_list_get ((GeeAbstractList*) _tmp12_, _tmp13_);
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
			actor = (ClutterActor*) _tmp14_;
#line 343 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp15_ = actor;
#line 343 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp16_ = clutter_actor_get_actions (_tmp15_);
#line 1459 "DragDropAction.c"
			{
				GList* action_collection = NULL;
				GList* action_it = NULL;
#line 343 "/home/nick/work/gala/src/DragDropAction.vala"
				action_collection = _tmp16_;
#line 343 "/home/nick/work/gala/src/DragDropAction.vala"
				for (action_it = action_collection; action_it != NULL; action_it = action_it->next) {
#line 1467 "DragDropAction.c"
					ClutterAction* action = NULL;
#line 343 "/home/nick/work/gala/src/DragDropAction.vala"
					action = (ClutterAction*) action_it->data;
#line 1471 "DragDropAction.c"
					{
						GalaDragDropAction* drag_action = NULL;
						ClutterAction* _tmp17_ = NULL;
						GalaDragDropAction* _tmp18_ = NULL;
						gboolean _tmp19_ = FALSE;
						GalaDragDropAction* _tmp20_ = NULL;
#line 344 "/home/nick/work/gala/src/DragDropAction.vala"
						_tmp17_ = action;
#line 344 "/home/nick/work/gala/src/DragDropAction.vala"
						_tmp18_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp17_, GALA_TYPE_DRAG_DROP_ACTION) ? ((GalaDragDropAction*) _tmp17_) : NULL);
#line 344 "/home/nick/work/gala/src/DragDropAction.vala"
						drag_action = _tmp18_;
#line 345 "/home/nick/work/gala/src/DragDropAction.vala"
						_tmp20_ = drag_action;
#line 345 "/home/nick/work/gala/src/DragDropAction.vala"
						if (_tmp20_ != NULL) {
#line 1488 "DragDropAction.c"
							GalaDragDropAction* _tmp21_ = NULL;
							gboolean _tmp22_ = FALSE;
#line 345 "/home/nick/work/gala/src/DragDropAction.vala"
							_tmp21_ = drag_action;
#line 345 "/home/nick/work/gala/src/DragDropAction.vala"
							_tmp22_ = _tmp21_->priv->_dragging;
#line 345 "/home/nick/work/gala/src/DragDropAction.vala"
							_tmp19_ = _tmp22_;
#line 1497 "DragDropAction.c"
						} else {
#line 345 "/home/nick/work/gala/src/DragDropAction.vala"
							_tmp19_ = FALSE;
#line 1501 "DragDropAction.c"
						}
#line 345 "/home/nick/work/gala/src/DragDropAction.vala"
						if (_tmp19_) {
#line 1505 "DragDropAction.c"
							GalaDragDropAction* _tmp23_ = NULL;
#line 346 "/home/nick/work/gala/src/DragDropAction.vala"
							_tmp23_ = drag_action;
#line 346 "/home/nick/work/gala/src/DragDropAction.vala"
							gala_drag_drop_action_cancel (_tmp23_);
#line 347 "/home/nick/work/gala/src/DragDropAction.vala"
							_g_object_unref0 (drag_action);
#line 347 "/home/nick/work/gala/src/DragDropAction.vala"
							break;
#line 1515 "DragDropAction.c"
						}
#line 343 "/home/nick/work/gala/src/DragDropAction.vala"
						_g_object_unref0 (drag_action);
#line 1519 "DragDropAction.c"
					}
				}
#line 343 "/home/nick/work/gala/src/DragDropAction.vala"
				_g_list_free0 (action_collection);
#line 1524 "DragDropAction.c"
			}
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
			_g_object_unref0 (actor);
#line 1528 "DragDropAction.c"
		}
#line 342 "/home/nick/work/gala/src/DragDropAction.vala"
		_g_object_unref0 (_actor_list);
#line 1532 "DragDropAction.c"
	}
#line 336 "/home/nick/work/gala/src/DragDropAction.vala"
	_g_object_unref0 (actors);
#line 1536 "DragDropAction.c"
}


static void gala_drag_drop_action_finish (GalaDragDropAction* self) {
	ClutterActor* _tmp0_ = NULL;
	ClutterActor* _tmp1_ = NULL;
#line 353 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (self != NULL);
#line 356 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = self->priv->hovered;
#line 356 "/home/nick/work/gala/src/DragDropAction.vala"
	gala_drag_drop_action_emit_crossed (self, _tmp0_, FALSE);
#line 358 "/home/nick/work/gala/src/DragDropAction.vala"
	gala_drag_drop_action_cleanup (self);
#line 360 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp1_ = self->priv->hovered;
#line 360 "/home/nick/work/gala/src/DragDropAction.vala"
	g_signal_emit_by_name (self, "drag-end", _tmp1_);
#line 1555 "DragDropAction.c"
}


static void gala_drag_drop_action_cleanup (GalaDragDropAction* self) {
	GeeLinkedList* source_list = NULL;
	GeeHashMap* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gpointer _tmp2_ = NULL;
	GeeLinkedList* _tmp3_ = NULL;
	gboolean _tmp16_ = FALSE;
#line 363 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (self != NULL);
#line 365 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = gala_drag_drop_action_sources;
#line 365 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp1_ = self->priv->_drag_id;
#line 365 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp2_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp0_, _tmp1_);
#line 365 "/home/nick/work/gala/src/DragDropAction.vala"
	source_list = (GeeLinkedList*) _tmp2_;
#line 366 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp3_ = source_list;
#line 366 "/home/nick/work/gala/src/DragDropAction.vala"
	if (_tmp3_ != NULL) {
#line 1580 "DragDropAction.c"
		{
			GeeLinkedList* _actor_list = NULL;
			GeeLinkedList* _tmp4_ = NULL;
			GeeLinkedList* _tmp5_ = NULL;
			gint _actor_size = 0;
			GeeLinkedList* _tmp6_ = NULL;
			gint _tmp7_ = 0;
			gint _tmp8_ = 0;
			gint _actor_index = 0;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp4_ = source_list;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp5_ = _g_object_ref0 (_tmp4_);
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
			_actor_list = _tmp5_;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp6_ = _actor_list;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp7_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp6_);
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
			_tmp8_ = _tmp7_;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
			_actor_size = _tmp8_;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
			_actor_index = -1;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
			while (TRUE) {
#line 1608 "DragDropAction.c"
				gint _tmp9_ = 0;
				gint _tmp10_ = 0;
				gint _tmp11_ = 0;
				ClutterActor* actor = NULL;
				GeeLinkedList* _tmp12_ = NULL;
				gint _tmp13_ = 0;
				gpointer _tmp14_ = NULL;
				ClutterActor* _tmp15_ = NULL;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp9_ = _actor_index;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
				_actor_index = _tmp9_ + 1;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp10_ = _actor_index;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp11_ = _actor_size;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
				if (!(_tmp10_ < _tmp11_)) {
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
					break;
#line 1629 "DragDropAction.c"
				}
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp12_ = _actor_list;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp13_ = _actor_index;
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp14_ = gee_abstract_list_get ((GeeAbstractList*) _tmp12_, _tmp13_);
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
				actor = (ClutterActor*) _tmp14_;
#line 368 "/home/nick/work/gala/src/DragDropAction.vala"
				_tmp15_ = actor;
#line 368 "/home/nick/work/gala/src/DragDropAction.vala"
				clutter_actor_set_reactive (_tmp15_, TRUE);
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
				_g_object_unref0 (actor);
#line 1645 "DragDropAction.c"
			}
#line 367 "/home/nick/work/gala/src/DragDropAction.vala"
			_g_object_unref0 (_actor_list);
#line 1649 "DragDropAction.c"
		}
	}
#line 372 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp16_ = self->priv->_dragging;
#line 372 "/home/nick/work/gala/src/DragDropAction.vala"
	if (_tmp16_) {
#line 1656 "DragDropAction.c"
		ClutterActor* _tmp17_ = NULL;
		ClutterActor* _tmp18_ = NULL;
		ClutterStage* _tmp19_ = NULL;
		guint _tmp20_ = 0U;
#line 373 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp17_ = clutter_actor_meta_get_actor ((ClutterActorMeta*) self);
#line 373 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp18_ = _tmp17_;
#line 373 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp19_ = clutter_actor_get_stage (_tmp18_);
#line 373 "/home/nick/work/gala/src/DragDropAction.vala"
		g_signal_parse_name ("captured-event", clutter_actor_get_type (), &_tmp20_, NULL, FALSE);
#line 373 "/home/nick/work/gala/src/DragDropAction.vala"
		g_signal_handlers_disconnect_matched ((ClutterActor*) _tmp19_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp20_, 0, NULL, (GCallback) _gala_drag_drop_action_follow_move_clutter_actor_captured_event, self);
#line 1671 "DragDropAction.c"
	}
#line 375 "/home/nick/work/gala/src/DragDropAction.vala"
	gala_drag_drop_action_set_dragging (self, FALSE);
#line 363 "/home/nick/work/gala/src/DragDropAction.vala"
	_g_object_unref0 (source_list);
#line 1677 "DragDropAction.c"
}


GalaDragDropActionType gala_drag_drop_action_get_drag_type (GalaDragDropAction* self) {
	GalaDragDropActionType result;
	GalaDragDropActionType _tmp0_ = 0;
#line 81 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 81 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = self->priv->_drag_type;
#line 81 "/home/nick/work/gala/src/DragDropAction.vala"
	result = _tmp0_;
#line 81 "/home/nick/work/gala/src/DragDropAction.vala"
	return result;
#line 1692 "DragDropAction.c"
}


static void gala_drag_drop_action_set_drag_type (GalaDragDropAction* self, GalaDragDropActionType value) {
	GalaDragDropActionType _tmp0_ = 0;
#line 81 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (self != NULL);
#line 81 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = value;
#line 81 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv->_drag_type = _tmp0_;
#line 81 "/home/nick/work/gala/src/DragDropAction.vala"
	g_object_notify ((GObject *) self, "drag-type");
#line 1706 "DragDropAction.c"
}


const gchar* gala_drag_drop_action_get_drag_id (GalaDragDropAction* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 86 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 86 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = self->priv->_drag_id;
#line 86 "/home/nick/work/gala/src/DragDropAction.vala"
	result = _tmp0_;
#line 86 "/home/nick/work/gala/src/DragDropAction.vala"
	return result;
#line 1721 "DragDropAction.c"
}


static void gala_drag_drop_action_set_drag_id (GalaDragDropAction* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 86 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (self != NULL);
#line 86 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = value;
#line 86 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 86 "/home/nick/work/gala/src/DragDropAction.vala"
	_g_free0 (self->priv->_drag_id);
#line 86 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv->_drag_id = _tmp1_;
#line 86 "/home/nick/work/gala/src/DragDropAction.vala"
	g_object_notify ((GObject *) self, "drag-id");
#line 1740 "DragDropAction.c"
}


ClutterActor* gala_drag_drop_action_get_handle (GalaDragDropAction* self) {
	ClutterActor* result;
	ClutterActor* _tmp0_ = NULL;
#line 88 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 88 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = self->priv->_handle;
#line 88 "/home/nick/work/gala/src/DragDropAction.vala"
	result = _tmp0_;
#line 88 "/home/nick/work/gala/src/DragDropAction.vala"
	return result;
#line 1755 "DragDropAction.c"
}


static void gala_drag_drop_action_set_handle (GalaDragDropAction* self, ClutterActor* value) {
	ClutterActor* _tmp0_ = NULL;
	ClutterActor* _tmp1_ = NULL;
#line 88 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (self != NULL);
#line 88 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = value;
#line 88 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 88 "/home/nick/work/gala/src/DragDropAction.vala"
	_g_object_unref0 (self->priv->_handle);
#line 88 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv->_handle = _tmp1_;
#line 88 "/home/nick/work/gala/src/DragDropAction.vala"
	g_object_notify ((GObject *) self, "handle");
#line 1774 "DragDropAction.c"
}


gboolean gala_drag_drop_action_get_dragging (GalaDragDropAction* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
#line 92 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 92 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = self->priv->_dragging;
#line 92 "/home/nick/work/gala/src/DragDropAction.vala"
	result = _tmp0_;
#line 92 "/home/nick/work/gala/src/DragDropAction.vala"
	return result;
#line 1789 "DragDropAction.c"
}


static void gala_drag_drop_action_set_dragging (GalaDragDropAction* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
#line 92 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (self != NULL);
#line 92 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = value;
#line 92 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv->_dragging = _tmp0_;
#line 92 "/home/nick/work/gala/src/DragDropAction.vala"
	g_object_notify ((GObject *) self, "dragging");
#line 1803 "DragDropAction.c"
}


gboolean gala_drag_drop_action_get_allow_bubbling (GalaDragDropAction* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
#line 98 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 98 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = self->priv->_allow_bubbling;
#line 98 "/home/nick/work/gala/src/DragDropAction.vala"
	result = _tmp0_;
#line 98 "/home/nick/work/gala/src/DragDropAction.vala"
	return result;
#line 1818 "DragDropAction.c"
}


void gala_drag_drop_action_set_allow_bubbling (GalaDragDropAction* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
#line 98 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (self != NULL);
#line 98 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = value;
#line 98 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv->_allow_bubbling = _tmp0_;
#line 98 "/home/nick/work/gala/src/DragDropAction.vala"
	g_object_notify ((GObject *) self, "allow-bubbling");
#line 1832 "DragDropAction.c"
}


static void g_cclosure_user_marshal_OBJECT__FLOAT_FLOAT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef gpointer (*GMarshalFunc_OBJECT__FLOAT_FLOAT) (gpointer data1, gfloat arg_1, gfloat arg_2, gpointer data2);
	register GMarshalFunc_OBJECT__FLOAT_FLOAT callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	gpointer v_return;
	cc = (GCClosure *) closure;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (return_value != NULL);
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (n_param_values == 3);
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	if (G_CCLOSURE_SWAP_DATA (closure)) {
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		data1 = closure->data;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		data2 = param_values->data[0].v_pointer;
#line 1854 "DragDropAction.c"
	} else {
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		data1 = param_values->data[0].v_pointer;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		data2 = closure->data;
#line 1860 "DragDropAction.c"
	}
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	callback = (GMarshalFunc_OBJECT__FLOAT_FLOAT) (marshal_data ? marshal_data : cc->callback);
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	v_return = callback (data1, g_value_get_float (param_values + 1), g_value_get_float (param_values + 2), data2);
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_value_take_object (return_value, v_return);
#line 1868 "DragDropAction.c"
}


static void g_cclosure_user_marshal_VOID__OBJECT_BOOLEAN (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__OBJECT_BOOLEAN) (gpointer data1, gpointer arg_1, gboolean arg_2, gpointer data2);
	register GMarshalFunc_VOID__OBJECT_BOOLEAN callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_return_if_fail (n_param_values == 3);
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	if (G_CCLOSURE_SWAP_DATA (closure)) {
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		data1 = closure->data;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		data2 = param_values->data[0].v_pointer;
#line 1887 "DragDropAction.c"
	} else {
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		data1 = param_values->data[0].v_pointer;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		data2 = closure->data;
#line 1893 "DragDropAction.c"
	}
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	callback = (GMarshalFunc_VOID__OBJECT_BOOLEAN) (marshal_data ? marshal_data : cc->callback);
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	callback (data1, g_value_get_object (param_values + 1), g_value_get_boolean (param_values + 2), data2);
#line 1899 "DragDropAction.c"
}


static void gala_drag_drop_action_class_init (GalaDragDropActionClass * klass) {
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	gala_drag_drop_action_parent_class = g_type_class_peek_parent (klass);
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_type_class_add_private (klass, sizeof (GalaDragDropActionPrivate));
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	((ClutterActorMetaClass *) klass)->set_actor = gala_drag_drop_action_real_set_actor;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_gala_drag_drop_action_get_property;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_gala_drag_drop_action_set_property;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	G_OBJECT_CLASS (klass)->finalize = gala_drag_drop_action_finalize;
#line 1916 "DragDropAction.c"
	/**
	 * The type of the action
	 */
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GALA_DRAG_DROP_ACTION_DRAG_TYPE, g_param_spec_enum ("drag-type", "drag-type", "drag-type", GALA_TYPE_DRAG_DROP_ACTION_TYPE, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 1922 "DragDropAction.c"
	/**
	 * The unique id given to this drag-drop-group
	 */
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GALA_DRAG_DROP_ACTION_DRAG_ID, g_param_spec_string ("drag-id", "drag-id", "drag-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GALA_DRAG_DROP_ACTION_HANDLE, g_param_spec_object ("handle", "handle", "handle", clutter_actor_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 1930 "DragDropAction.c"
	/**
	 * Indicates whether a drag action is currently active
	 */
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GALA_DRAG_DROP_ACTION_DRAGGING, g_param_spec_boolean ("dragging", "dragging", "dragging", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 1936 "DragDropAction.c"
	/**
	 * Allow checking the parents of reactive children if they are valid destinations
	 * if the child is none
	 */
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), GALA_DRAG_DROP_ACTION_ALLOW_BUBBLING, g_param_spec_boolean ("allow-bubbling", "allow-bubbling", "allow-bubbling", TRUE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 1943 "DragDropAction.c"
	/**
	 * A drag has been started. You have to connect to this signal and
	 * return an actor that is transformed during the drag operation.
	 *
	 * @param x The global x coordinate where the action was activated
	 * @param y The global y coordinate where the action was activated
	 * @return  A ClutterActor that serves as handle
	 */
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_signal_new ("drag_begin", GALA_TYPE_DRAG_DROP_ACTION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_OBJECT__FLOAT_FLOAT, clutter_actor_get_type (), 2, G_TYPE_FLOAT, G_TYPE_FLOAT);
#line 1954 "DragDropAction.c"
	/**
	 * A drag has been canceled. You may want to consider cleaning up
	 * your handle.
	 */
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_signal_new ("drag_canceled", GALA_TYPE_DRAG_DROP_ACTION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 1961 "DragDropAction.c"
	/**
	 * A drag action has successfully been finished.
	 *
	 * @param actor The actor on which the drag finished
	 */
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_signal_new ("drag_end", GALA_TYPE_DRAG_DROP_ACTION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, clutter_actor_get_type ());
#line 1969 "DragDropAction.c"
	/**
	 * The destination has been crossed
	 *
	 * @param hovered indicates whether the actor is now hovered or not
	 */
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_signal_new ("crossed", GALA_TYPE_DRAG_DROP_ACTION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOOLEAN, G_TYPE_NONE, 1, G_TYPE_BOOLEAN);
#line 1977 "DragDropAction.c"
	/**
	 * Emitted on the source when a destination is crossed.
	 *
	 * @param destination The destination actor that has been crossed
	 * @param hovered     Whether the actor is now hovered or has just been left
	 */
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_signal_new ("destination_crossed", GALA_TYPE_DRAG_DROP_ACTION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__OBJECT_BOOLEAN, G_TYPE_NONE, 2, clutter_actor_get_type (), G_TYPE_BOOLEAN);
#line 1986 "DragDropAction.c"
	/**
	 * The source has been clicked, but the movement was not larger than
	 * the drag threshold. Useful if the source is also activable.
	 *
	 * @param button The button which was pressed
	 */
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	g_signal_new ("actor_clicked", GALA_TYPE_DRAG_DROP_ACTION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__UINT, G_TYPE_NONE, 1, G_TYPE_UINT);
#line 1995 "DragDropAction.c"
}


static void gala_drag_drop_action_instance_init (GalaDragDropAction * self) {
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv = GALA_DRAG_DROP_ACTION_GET_PRIVATE (self);
#line 92 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv->_dragging = FALSE;
#line 98 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv->_allow_bubbling = TRUE;
#line 100 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv->hovered = NULL;
#line 101 "/home/nick/work/gala/src/DragDropAction.vala"
	self->priv->clicked = FALSE;
#line 2010 "DragDropAction.c"
}


static void gala_drag_drop_action_finalize (GObject* obj) {
	GalaDragDropAction * self;
	ClutterActor* _tmp0_ = NULL;
	ClutterActor* _tmp1_ = NULL;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GALA_TYPE_DRAG_DROP_ACTION, GalaDragDropAction);
#line 123 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp0_ = clutter_actor_meta_get_actor ((ClutterActorMeta*) self);
#line 123 "/home/nick/work/gala/src/DragDropAction.vala"
	_tmp1_ = _tmp0_;
#line 123 "/home/nick/work/gala/src/DragDropAction.vala"
	if (_tmp1_ != NULL) {
#line 2026 "DragDropAction.c"
		ClutterActor* _tmp2_ = NULL;
		ClutterActor* _tmp3_ = NULL;
#line 124 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp2_ = clutter_actor_meta_get_actor ((ClutterActorMeta*) self);
#line 124 "/home/nick/work/gala/src/DragDropAction.vala"
		_tmp3_ = _tmp2_;
#line 124 "/home/nick/work/gala/src/DragDropAction.vala"
		gala_drag_drop_action_release_actor (self, _tmp3_);
#line 2035 "DragDropAction.c"
	}
#line 86 "/home/nick/work/gala/src/DragDropAction.vala"
	_g_free0 (self->priv->_drag_id);
#line 88 "/home/nick/work/gala/src/DragDropAction.vala"
	_g_object_unref0 (self->priv->_handle);
#line 100 "/home/nick/work/gala/src/DragDropAction.vala"
	_g_object_unref0 (self->priv->hovered);
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	G_OBJECT_CLASS (gala_drag_drop_action_parent_class)->finalize (obj);
#line 2045 "DragDropAction.c"
}


GType gala_drag_drop_action_get_type (void) {
	static volatile gsize gala_drag_drop_action_type_id__volatile = 0;
	if (g_once_init_enter (&gala_drag_drop_action_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GalaDragDropActionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gala_drag_drop_action_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GalaDragDropAction), 0, (GInstanceInitFunc) gala_drag_drop_action_instance_init, NULL };
		GType gala_drag_drop_action_type_id;
		gala_drag_drop_action_type_id = g_type_register_static (clutter_action_get_type (), "GalaDragDropAction", &g_define_type_info, 0);
		g_once_init_leave (&gala_drag_drop_action_type_id__volatile, gala_drag_drop_action_type_id);
	}
	return gala_drag_drop_action_type_id__volatile;
}


static void _vala_gala_drag_drop_action_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GalaDragDropAction * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GALA_TYPE_DRAG_DROP_ACTION, GalaDragDropAction);
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	switch (property_id) {
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		case GALA_DRAG_DROP_ACTION_DRAG_TYPE:
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		g_value_set_enum (value, gala_drag_drop_action_get_drag_type (self));
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		case GALA_DRAG_DROP_ACTION_DRAG_ID:
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		g_value_set_string (value, gala_drag_drop_action_get_drag_id (self));
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		case GALA_DRAG_DROP_ACTION_HANDLE:
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		g_value_set_object (value, gala_drag_drop_action_get_handle (self));
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		case GALA_DRAG_DROP_ACTION_DRAGGING:
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		g_value_set_boolean (value, gala_drag_drop_action_get_dragging (self));
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		case GALA_DRAG_DROP_ACTION_ALLOW_BUBBLING:
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		g_value_set_boolean (value, gala_drag_drop_action_get_allow_bubbling (self));
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 2096 "DragDropAction.c"
		default:
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 2102 "DragDropAction.c"
	}
}


static void _vala_gala_drag_drop_action_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GalaDragDropAction * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GALA_TYPE_DRAG_DROP_ACTION, GalaDragDropAction);
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
	switch (property_id) {
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		case GALA_DRAG_DROP_ACTION_DRAG_TYPE:
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		gala_drag_drop_action_set_drag_type (self, g_value_get_enum (value));
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		case GALA_DRAG_DROP_ACTION_DRAG_ID:
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		gala_drag_drop_action_set_drag_id (self, g_value_get_string (value));
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		case GALA_DRAG_DROP_ACTION_HANDLE:
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		gala_drag_drop_action_set_handle (self, g_value_get_object (value));
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		case GALA_DRAG_DROP_ACTION_DRAGGING:
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		gala_drag_drop_action_set_dragging (self, g_value_get_boolean (value));
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		case GALA_DRAG_DROP_ACTION_ALLOW_BUBBLING:
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		gala_drag_drop_action_set_allow_bubbling (self, g_value_get_boolean (value));
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 2142 "DragDropAction.c"
		default:
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 28 "/home/nick/work/gala/src/DragDropAction.vala"
		break;
#line 2148 "DragDropAction.c"
	}
}



