/* volume-service.c generated by valac 0.30.1, the Vala compiler
 * generated from volume-service.vala, do not modify */

/*
 * Copyright (C) 2010 Michal Hruby <michal.mhr@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authored by Michal Hruby <michal.mhr@gmail.com>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define SYNAPSE_TYPE_VOLUME_SERVICE (synapse_volume_service_get_type ())
#define SYNAPSE_VOLUME_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_TYPE_VOLUME_SERVICE, SynapseVolumeService))
#define SYNAPSE_VOLUME_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_TYPE_VOLUME_SERVICE, SynapseVolumeServiceClass))
#define SYNAPSE_IS_VOLUME_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_TYPE_VOLUME_SERVICE))
#define SYNAPSE_IS_VOLUME_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_TYPE_VOLUME_SERVICE))
#define SYNAPSE_VOLUME_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_TYPE_VOLUME_SERVICE, SynapseVolumeServiceClass))

typedef struct _SynapseVolumeService SynapseVolumeService;
typedef struct _SynapseVolumeServiceClass SynapseVolumeServiceClass;
typedef struct _SynapseVolumeServicePrivate SynapseVolumeServicePrivate;

#define SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT (synapse_volume_service_volume_object_get_type ())
#define SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObject))
#define SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObjectClass))
#define SYNAPSE_VOLUME_SERVICE_IS_VOLUME_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT))
#define SYNAPSE_VOLUME_SERVICE_IS_VOLUME_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT))
#define SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObjectClass))

typedef struct _SynapseVolumeServiceVolumeObject SynapseVolumeServiceVolumeObject;
typedef struct _SynapseVolumeServiceVolumeObjectClass SynapseVolumeServiceVolumeObjectClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define SYNAPSE_TYPE_MATCH (synapse_match_get_type ())
#define SYNAPSE_MATCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_TYPE_MATCH, SynapseMatch))
#define SYNAPSE_IS_MATCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_TYPE_MATCH))
#define SYNAPSE_MATCH_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYNAPSE_TYPE_MATCH, SynapseMatchIface))

typedef struct _SynapseMatch SynapseMatch;
typedef struct _SynapseMatchIface SynapseMatchIface;

#define SYNAPSE_TYPE_QUERY_FLAGS (synapse_query_flags_get_type ())

#define SYNAPSE_TYPE_MATCH_TYPE (synapse_match_type_get_type ())

#define SYNAPSE_TYPE_URI_MATCH (synapse_uri_match_get_type ())
#define SYNAPSE_URI_MATCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SYNAPSE_TYPE_URI_MATCH, SynapseUriMatch))
#define SYNAPSE_IS_URI_MATCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SYNAPSE_TYPE_URI_MATCH))
#define SYNAPSE_URI_MATCH_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), SYNAPSE_TYPE_URI_MATCH, SynapseUriMatchIface))

typedef struct _SynapseUriMatch SynapseUriMatch;
typedef struct _SynapseUriMatchIface SynapseUriMatchIface;
typedef struct _SynapseVolumeServiceVolumeObjectPrivate SynapseVolumeServiceVolumeObjectPrivate;

struct _SynapseVolumeService {
	GObject parent_instance;
	SynapseVolumeServicePrivate * priv;
};

struct _SynapseVolumeServiceClass {
	GObjectClass parent_class;
};

struct _SynapseVolumeServicePrivate {
	GVolumeMonitor* vm;
	GeeMap* volumes;
};

typedef enum  {
	SYNAPSE_QUERY_FLAGS_INCLUDE_REMOTE = 1 << 0,
	SYNAPSE_QUERY_FLAGS_UNCATEGORIZED = 1 << 1,
	SYNAPSE_QUERY_FLAGS_APPLICATIONS = 1 << 2,
	SYNAPSE_QUERY_FLAGS_ACTIONS = 1 << 3,
	SYNAPSE_QUERY_FLAGS_AUDIO = 1 << 4,
	SYNAPSE_QUERY_FLAGS_VIDEO = 1 << 5,
	SYNAPSE_QUERY_FLAGS_DOCUMENTS = 1 << 6,
	SYNAPSE_QUERY_FLAGS_IMAGES = 1 << 7,
	SYNAPSE_QUERY_FLAGS_FILES = ((SYNAPSE_QUERY_FLAGS_AUDIO | SYNAPSE_QUERY_FLAGS_VIDEO) | SYNAPSE_QUERY_FLAGS_DOCUMENTS) | SYNAPSE_QUERY_FLAGS_IMAGES,
	SYNAPSE_QUERY_FLAGS_PLACES = 1 << 8,
	SYNAPSE_QUERY_FLAGS_INTERNET = 1 << 9,
	SYNAPSE_QUERY_FLAGS_TEXT = 1 << 10,
	SYNAPSE_QUERY_FLAGS_CONTACTS = 1 << 11,
	SYNAPSE_QUERY_FLAGS_ALL = 0xFFFFFFFFLL,
	SYNAPSE_QUERY_FLAGS_LOCAL_CONTENT = SYNAPSE_QUERY_FLAGS_ALL ^ SYNAPSE_QUERY_FLAGS_INCLUDE_REMOTE
} SynapseQueryFlags;

typedef enum  {
	SYNAPSE_MATCH_TYPE_UNKNOWN = 0,
	SYNAPSE_MATCH_TYPE_TEXT,
	SYNAPSE_MATCH_TYPE_APPLICATION,
	SYNAPSE_MATCH_TYPE_GENERIC_URI,
	SYNAPSE_MATCH_TYPE_ACTION,
	SYNAPSE_MATCH_TYPE_SEARCH,
	SYNAPSE_MATCH_TYPE_CONTACT
} SynapseMatchType;

struct _SynapseMatchIface {
	GTypeInterface parent_iface;
	void (*execute) (SynapseMatch* self, SynapseMatch* match);
	void (*execute_with_target) (SynapseMatch* self, SynapseMatch* source, SynapseMatch* target);
	gboolean (*needs_target) (SynapseMatch* self);
	SynapseQueryFlags (*target_flags) (SynapseMatch* self);
	const gchar* (*get_title) (SynapseMatch* self);
	void (*set_title) (SynapseMatch* self, const gchar* value);
	const gchar* (*get_description) (SynapseMatch* self);
	void (*set_description) (SynapseMatch* self, const gchar* value);
	const gchar* (*get_icon_name) (SynapseMatch* self);
	void (*set_icon_name) (SynapseMatch* self, const gchar* value);
	gboolean (*get_has_thumbnail) (SynapseMatch* self);
	void (*set_has_thumbnail) (SynapseMatch* self, gboolean value);
	const gchar* (*get_thumbnail_path) (SynapseMatch* self);
	void (*set_thumbnail_path) (SynapseMatch* self, const gchar* value);
	SynapseMatchType (*get_match_type) (SynapseMatch* self);
	void (*set_match_type) (SynapseMatch* self, SynapseMatchType value);
};

struct _SynapseUriMatchIface {
	GTypeInterface parent_iface;
	const gchar* (*get_uri) (SynapseUriMatch* self);
	void (*set_uri) (SynapseUriMatch* self, const gchar* value);
	SynapseQueryFlags (*get_file_type) (SynapseUriMatch* self);
	void (*set_file_type) (SynapseUriMatch* self, SynapseQueryFlags value);
	const gchar* (*get_mime_type) (SynapseUriMatch* self);
	void (*set_mime_type) (SynapseUriMatch* self, const gchar* value);
};

struct _SynapseVolumeServiceVolumeObject {
	GObject parent_instance;
	SynapseVolumeServiceVolumeObjectPrivate * priv;
};

struct _SynapseVolumeServiceVolumeObjectClass {
	GObjectClass parent_class;
};

struct _SynapseVolumeServiceVolumeObjectPrivate {
	gchar* _title;
	gchar* _description;
	gchar* _icon_name;
	gboolean _has_thumbnail;
	gchar* _thumbnail_path;
	SynapseMatchType _match_type;
	gchar* _uri;
	SynapseQueryFlags _file_type;
	gchar* _mime_type;
	gulong changed_signal_id;
	GVolume* _volume;
};


static gpointer synapse_volume_service_parent_class = NULL;
static SynapseVolumeService* synapse_volume_service_instance;
static SynapseVolumeService* synapse_volume_service_instance = NULL;
static gpointer synapse_volume_service_volume_object_parent_class = NULL;
static SynapseMatchIface* synapse_volume_service_volume_object_synapse_match_parent_iface = NULL;
static SynapseUriMatchIface* synapse_volume_service_volume_object_synapse_uri_match_parent_iface = NULL;

GType synapse_volume_service_get_type (void) G_GNUC_CONST;
GType synapse_volume_service_volume_object_get_type (void) G_GNUC_CONST;
#define SYNAPSE_VOLUME_SERVICE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNAPSE_TYPE_VOLUME_SERVICE, SynapseVolumeServicePrivate))
enum  {
	SYNAPSE_VOLUME_SERVICE_DUMMY_PROPERTY
};
SynapseVolumeService* synapse_volume_service_get_default (void);
static SynapseVolumeService* synapse_volume_service_new (void);
static SynapseVolumeService* synapse_volume_service_construct (GType object_type);
void synapse_volume_service_initialize (SynapseVolumeService* self);
static void __lambda11_ (SynapseVolumeService* self, GVolume* volume);
SynapseVolumeServiceVolumeObject* synapse_volume_service_volume_object_new (GVolume* volume);
SynapseVolumeServiceVolumeObject* synapse_volume_service_volume_object_construct (GType object_type, GVolume* volume);
static void ___lambda11__g_volume_monitor_volume_added (GVolumeMonitor* _sender, GVolume* volume, gpointer self);
static void __lambda12_ (SynapseVolumeService* self, GVolume* volume);
static void ___lambda12__g_volume_monitor_volume_removed (GVolumeMonitor* _sender, GVolume* volume, gpointer self);
static void __lambda13_ (SynapseVolumeService* self, GMount* mount);
void synapse_volume_service_volume_object_update_state (SynapseVolumeServiceVolumeObject* self);
static void ___lambda13__g_volume_monitor_mount_added (GVolumeMonitor* _sender, GMount* mount, gpointer self);
static void synapse_volume_service_process_volume_list (SynapseVolumeService* self, GList* volume_list);
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
GeeCollection* synapse_volume_service_get_volumes (SynapseVolumeService* self);
gchar* synapse_volume_service_uri_to_volume_name (SynapseVolumeService* self, const gchar* uri, gchar** volume_path);
static GObject * synapse_volume_service_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
GType synapse_query_flags_get_type (void) G_GNUC_CONST;
GType synapse_match_type_get_type (void) G_GNUC_CONST;
GType synapse_match_get_type (void) G_GNUC_CONST;
GType synapse_uri_match_get_type (void) G_GNUC_CONST;
#define SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObjectPrivate))
enum  {
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_DUMMY_PROPERTY,
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_TITLE,
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_DESCRIPTION,
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_ICON_NAME,
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_HAS_THUMBNAIL,
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_THUMBNAIL_PATH,
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_MATCH_TYPE,
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_URI,
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_FILE_TYPE,
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_MIME_TYPE,
	SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_VOLUME
};
void synapse_volume_service_volume_object_set_volume (SynapseVolumeServiceVolumeObject* self, GVolume* value);
gboolean synapse_volume_service_volume_object_is_mounted (SynapseVolumeServiceVolumeObject* self);
GVolume* synapse_volume_service_volume_object_get_volume (SynapseVolumeServiceVolumeObject* self);
void synapse_match_set_title (SynapseMatch* self, const gchar* value);
void synapse_match_set_description (SynapseMatch* self, const gchar* value);
void synapse_match_set_icon_name (SynapseMatch* self, const gchar* value);
void synapse_match_set_has_thumbnail (SynapseMatch* self, gboolean value);
void synapse_match_set_match_type (SynapseMatch* self, SynapseMatchType value);
SynapseMatchType synapse_match_get_match_type (SynapseMatch* self);
void synapse_uri_match_set_uri (SynapseUriMatch* self, const gchar* value);
void synapse_uri_match_set_file_type (SynapseUriMatch* self, SynapseQueryFlags value);
void synapse_uri_match_set_mime_type (SynapseUriMatch* self, const gchar* value);
static void _synapse_volume_service_volume_object_update_state_g_volume_changed (GVolume* _sender, gpointer self);
void synapse_utils_logger_debug (GObject* obj, const gchar* format, ...);
const gchar* synapse_match_get_title (SynapseMatch* self);
const gchar* synapse_match_get_icon_name (SynapseMatch* self);
const gchar* synapse_uri_match_get_uri (SynapseUriMatch* self);
static void synapse_volume_service_volume_object_finalize (GObject* obj);
const gchar* synapse_match_get_description (SynapseMatch* self);
gboolean synapse_match_get_has_thumbnail (SynapseMatch* self);
const gchar* synapse_match_get_thumbnail_path (SynapseMatch* self);
SynapseQueryFlags synapse_uri_match_get_file_type (SynapseUriMatch* self);
const gchar* synapse_uri_match_get_mime_type (SynapseUriMatch* self);
static void _vala_synapse_volume_service_volume_object_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
void synapse_match_set_thumbnail_path (SynapseMatch* self, const gchar* value);
static void _vala_synapse_volume_service_volume_object_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void synapse_volume_service_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


SynapseVolumeService* synapse_volume_service_get_default (void) {
	SynapseVolumeService* result = NULL;
	SynapseVolumeService* _tmp0_ = NULL;
	SynapseVolumeService* _tmp1_ = NULL;
	SynapseVolumeService* _tmp2_ = NULL;
	SynapseVolumeService* _tmp4_ = NULL;
	_tmp1_ = synapse_volume_service_instance;
	_tmp2_ = _g_object_ref0 (_tmp1_);
	_tmp0_ = _tmp2_;
	if (_tmp0_ == NULL) {
		SynapseVolumeService* _tmp3_ = NULL;
		_tmp3_ = synapse_volume_service_new ();
		_g_object_unref0 (_tmp0_);
		_tmp0_ = _tmp3_;
	}
	_tmp4_ = _tmp0_;
	_tmp0_ = NULL;
	result = _tmp4_;
	_g_object_unref0 (_tmp0_);
	return result;
}


static SynapseVolumeService* synapse_volume_service_construct (GType object_type) {
	SynapseVolumeService * self = NULL;
	self = (SynapseVolumeService*) g_object_new (object_type, NULL);
	return self;
}


static SynapseVolumeService* synapse_volume_service_new (void) {
	return synapse_volume_service_construct (SYNAPSE_TYPE_VOLUME_SERVICE);
}


static void __lambda11_ (SynapseVolumeService* self, GVolume* volume) {
	GeeMap* _tmp0_ = NULL;
	GVolume* _tmp1_ = NULL;
	GVolume* _tmp2_ = NULL;
	SynapseVolumeServiceVolumeObject* _tmp3_ = NULL;
	SynapseVolumeServiceVolumeObject* _tmp4_ = NULL;
	g_return_if_fail (volume != NULL);
	_tmp0_ = self->priv->volumes;
	_tmp1_ = volume;
	_tmp2_ = volume;
	_tmp3_ = synapse_volume_service_volume_object_new (_tmp2_);
	_tmp4_ = _tmp3_;
	gee_map_set (_tmp0_, _tmp1_, _tmp4_);
	_g_object_unref0 (_tmp4_);
}


static void ___lambda11__g_volume_monitor_volume_added (GVolumeMonitor* _sender, GVolume* volume, gpointer self) {
	__lambda11_ ((SynapseVolumeService*) self, volume);
}


static void __lambda12_ (SynapseVolumeService* self, GVolume* volume) {
	GeeMap* _tmp0_ = NULL;
	GVolume* _tmp1_ = NULL;
	g_return_if_fail (volume != NULL);
	_tmp0_ = self->priv->volumes;
	_tmp1_ = volume;
	gee_map_unset (_tmp0_, _tmp1_, NULL);
}


static void ___lambda12__g_volume_monitor_volume_removed (GVolumeMonitor* _sender, GVolume* volume, gpointer self) {
	__lambda12_ ((SynapseVolumeService*) self, volume);
}


static void __lambda13_ (SynapseVolumeService* self, GMount* mount) {
	GVolume* volume = NULL;
	GMount* _tmp0_ = NULL;
	GVolume* _tmp1_ = NULL;
	GVolume* _tmp2_ = NULL;
	GeeMap* _tmp3_ = NULL;
	GeeSet* _tmp4_ = NULL;
	GeeSet* _tmp5_ = NULL;
	GeeSet* _tmp6_ = NULL;
	GVolume* _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	gboolean _tmp9_ = FALSE;
	g_return_if_fail (mount != NULL);
	_tmp0_ = mount;
	_tmp1_ = g_mount_get_volume (_tmp0_);
	volume = _tmp1_;
	_tmp2_ = volume;
	if (_tmp2_ == NULL) {
		_g_object_unref0 (volume);
		return;
	}
	_tmp3_ = self->priv->volumes;
	_tmp4_ = gee_map_get_keys (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = _tmp5_;
	_tmp7_ = volume;
	_tmp8_ = gee_collection_contains ((GeeCollection*) _tmp6_, _tmp7_);
	_tmp9_ = _tmp8_;
	_g_object_unref0 (_tmp6_);
	if (_tmp9_) {
		GeeMap* _tmp10_ = NULL;
		GVolume* _tmp11_ = NULL;
		gpointer _tmp12_ = NULL;
		SynapseVolumeServiceVolumeObject* _tmp13_ = NULL;
		_tmp10_ = self->priv->volumes;
		_tmp11_ = volume;
		_tmp12_ = gee_map_get (_tmp10_, _tmp11_);
		_tmp13_ = (SynapseVolumeServiceVolumeObject*) _tmp12_;
		synapse_volume_service_volume_object_update_state (_tmp13_);
		_g_object_unref0 (_tmp13_);
	}
	_g_object_unref0 (volume);
}


static void ___lambda13__g_volume_monitor_mount_added (GVolumeMonitor* _sender, GMount* mount, gpointer self) {
	__lambda13_ ((SynapseVolumeService*) self, mount);
}


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_list_free__g_object_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_list_free (self);
}


void synapse_volume_service_initialize (SynapseVolumeService* self) {
	GVolumeMonitor* _tmp0_ = NULL;
	GVolumeMonitor* _tmp1_ = NULL;
	GVolumeMonitor* _tmp2_ = NULL;
	GVolumeMonitor* _tmp3_ = NULL;
	GList* volume_list = NULL;
	GVolumeMonitor* _tmp4_ = NULL;
	GList* _tmp5_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_volume_monitor_get ();
	_g_object_unref0 (self->priv->vm);
	self->priv->vm = _tmp0_;
	_tmp1_ = self->priv->vm;
	g_signal_connect_object (_tmp1_, "volume-added", (GCallback) ___lambda11__g_volume_monitor_volume_added, self, 0);
	_tmp2_ = self->priv->vm;
	g_signal_connect_object (_tmp2_, "volume-removed", (GCallback) ___lambda12__g_volume_monitor_volume_removed, self, 0);
	_tmp3_ = self->priv->vm;
	g_signal_connect_object (_tmp3_, "mount-added", (GCallback) ___lambda13__g_volume_monitor_mount_added, self, 0);
	_tmp4_ = self->priv->vm;
	_tmp5_ = g_volume_monitor_get_volumes (_tmp4_);
	volume_list = _tmp5_;
	synapse_volume_service_process_volume_list (self, volume_list);
	__g_list_free__g_object_unref0_0 (volume_list);
}


static void synapse_volume_service_process_volume_list (SynapseVolumeService* self, GList* volume_list) {
	GList* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = volume_list;
	{
		GList* volume_collection = NULL;
		GList* volume_it = NULL;
		volume_collection = _tmp0_;
		for (volume_it = volume_collection; volume_it != NULL; volume_it = volume_it->next) {
			GVolume* volume = NULL;
			volume = (GVolume*) volume_it->data;
			{
				GeeMap* _tmp1_ = NULL;
				GVolume* _tmp2_ = NULL;
				GVolume* _tmp3_ = NULL;
				SynapseVolumeServiceVolumeObject* _tmp4_ = NULL;
				SynapseVolumeServiceVolumeObject* _tmp5_ = NULL;
				_tmp1_ = self->priv->volumes;
				_tmp2_ = volume;
				_tmp3_ = volume;
				_tmp4_ = synapse_volume_service_volume_object_new (_tmp3_);
				_tmp5_ = _tmp4_;
				gee_map_set (_tmp1_, _tmp2_, _tmp5_);
				_g_object_unref0 (_tmp5_);
			}
		}
	}
}


GeeCollection* synapse_volume_service_get_volumes (SynapseVolumeService* self) {
	GeeCollection* result = NULL;
	GeeMap* _tmp0_ = NULL;
	GeeCollection* _tmp1_ = NULL;
	GeeCollection* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->volumes;
	_tmp1_ = gee_map_get_values (_tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}


gchar* synapse_volume_service_uri_to_volume_name (SynapseVolumeService* self, const gchar* uri, gchar** volume_path) {
	gchar* _vala_volume_path = NULL;
	gchar* result = NULL;
	GeeSet* g_volumes = NULL;
	GeeMap* _tmp0_ = NULL;
	GeeSet* _tmp1_ = NULL;
	GeeSet* _tmp2_ = NULL;
	GFile* f = NULL;
	const gchar* _tmp3_ = NULL;
	GFile* _tmp4_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (uri != NULL, NULL);
	_g_free0 (_vala_volume_path);
	_vala_volume_path = NULL;
	_tmp0_ = self->priv->volumes;
	_tmp1_ = gee_map_get_keys (_tmp0_);
	_tmp2_ = _tmp1_;
	g_volumes = _tmp2_;
	_tmp3_ = uri;
	_tmp4_ = g_file_new_for_uri (_tmp3_);
	f = _tmp4_;
	{
		GeeIterator* _volume_it = NULL;
		GeeSet* _tmp5_ = NULL;
		GeeIterator* _tmp6_ = NULL;
		_tmp5_ = g_volumes;
		_tmp6_ = gee_iterable_iterator ((GeeIterable*) _tmp5_);
		_volume_it = _tmp6_;
		while (TRUE) {
			GeeIterator* _tmp7_ = NULL;
			gboolean _tmp8_ = FALSE;
			GVolume* volume = NULL;
			GeeIterator* _tmp9_ = NULL;
			gpointer _tmp10_ = NULL;
			GFile* root = NULL;
			GVolume* _tmp11_ = NULL;
			GFile* _tmp12_ = NULL;
			GFile* _tmp13_ = NULL;
			GFile* _tmp19_ = NULL;
			GFile* _tmp20_ = NULL;
			gboolean _tmp21_ = FALSE;
			_tmp7_ = _volume_it;
			_tmp8_ = gee_iterator_next (_tmp7_);
			if (!_tmp8_) {
				break;
			}
			_tmp9_ = _volume_it;
			_tmp10_ = gee_iterator_get (_tmp9_);
			volume = (GVolume*) _tmp10_;
			_tmp11_ = volume;
			_tmp12_ = g_volume_get_activation_root (_tmp11_);
			root = _tmp12_;
			_tmp13_ = root;
			if (_tmp13_ == NULL) {
				GMount* mount = NULL;
				GVolume* _tmp14_ = NULL;
				GMount* _tmp15_ = NULL;
				GMount* _tmp16_ = NULL;
				GMount* _tmp17_ = NULL;
				GFile* _tmp18_ = NULL;
				_tmp14_ = volume;
				_tmp15_ = g_volume_get_mount (_tmp14_);
				mount = _tmp15_;
				_tmp16_ = mount;
				if (_tmp16_ == NULL) {
					_g_object_unref0 (mount);
					_g_object_unref0 (root);
					_g_object_unref0 (volume);
					continue;
				}
				_tmp17_ = mount;
				_tmp18_ = g_mount_get_root (_tmp17_);
				_g_object_unref0 (root);
				root = _tmp18_;
				_g_object_unref0 (mount);
			}
			_tmp19_ = f;
			_tmp20_ = root;
			_tmp21_ = g_file_has_prefix (_tmp19_, _tmp20_);
			if (_tmp21_) {
				GFile* _tmp22_ = NULL;
				gchar* _tmp23_ = NULL;
				GVolume* _tmp24_ = NULL;
				gchar* _tmp25_ = NULL;
				_tmp22_ = root;
				_tmp23_ = g_file_get_path (_tmp22_);
				_g_free0 (_vala_volume_path);
				_vala_volume_path = _tmp23_;
				_tmp24_ = volume;
				_tmp25_ = g_volume_get_name (_tmp24_);
				result = _tmp25_;
				_g_object_unref0 (root);
				_g_object_unref0 (volume);
				_g_object_unref0 (_volume_it);
				_g_object_unref0 (f);
				_g_object_unref0 (g_volumes);
				if (volume_path) {
					*volume_path = _vala_volume_path;
				} else {
					_g_free0 (_vala_volume_path);
				}
				return result;
			}
			_g_object_unref0 (root);
			_g_object_unref0 (volume);
		}
		_g_object_unref0 (_volume_it);
	}
	result = NULL;
	_g_object_unref0 (f);
	_g_object_unref0 (g_volumes);
	if (volume_path) {
		*volume_path = _vala_volume_path;
	} else {
		_g_free0 (_vala_volume_path);
	}
	return result;
}


static GObject * synapse_volume_service_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	SynapseVolumeService * self;
	GeeHashMap* _tmp0_ = NULL;
	parent_class = G_OBJECT_CLASS (synapse_volume_service_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_TYPE_VOLUME_SERVICE, SynapseVolumeService);
	synapse_volume_service_instance = self;
	_tmp0_ = gee_hash_map_new (g_volume_get_type (), (GBoxedCopyFunc) g_object_ref, g_object_unref, SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->volumes);
	self->priv->volumes = (GeeMap*) _tmp0_;
	synapse_volume_service_initialize (self);
	return obj;
}


void synapse_volume_service_volume_object_update_state (SynapseVolumeServiceVolumeObject* self) {
	GVolume* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_volume;
	synapse_volume_service_volume_object_set_volume (self, _tmp0_);
}


gboolean synapse_volume_service_volume_object_is_mounted (SynapseVolumeServiceVolumeObject* self) {
	gboolean result = FALSE;
	GVolume* _tmp0_ = NULL;
	GMount* _tmp1_ = NULL;
	GMount* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_volume;
	_tmp1_ = g_volume_get_mount (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = _tmp2_ != NULL;
	_g_object_unref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


SynapseVolumeServiceVolumeObject* synapse_volume_service_volume_object_construct (GType object_type, GVolume* volume) {
	SynapseVolumeServiceVolumeObject * self = NULL;
	GVolume* _tmp0_ = NULL;
	g_return_val_if_fail (volume != NULL, NULL);
	_tmp0_ = volume;
	self = (SynapseVolumeServiceVolumeObject*) g_object_new (object_type, "volume", _tmp0_, NULL);
	return self;
}


SynapseVolumeServiceVolumeObject* synapse_volume_service_volume_object_new (GVolume* volume) {
	return synapse_volume_service_volume_object_construct (SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, volume);
}


static const gchar* synapse_volume_service_volume_object_real_get_title (SynapseMatch* base) {
	const gchar* result;
	SynapseVolumeServiceVolumeObject* self;
	const gchar* _tmp0_ = NULL;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = self->priv->_title;
	result = _tmp0_;
	return result;
}


static void synapse_volume_service_volume_object_real_set_title (SynapseMatch* base, const gchar* value) {
	SynapseVolumeServiceVolumeObject* self;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_title);
	self->priv->_title = _tmp1_;
	g_object_notify ((GObject *) self, "title");
}


static const gchar* synapse_volume_service_volume_object_real_get_description (SynapseMatch* base) {
	const gchar* result;
	SynapseVolumeServiceVolumeObject* self;
	const gchar* _tmp0_ = NULL;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = self->priv->_description;
	result = _tmp0_;
	return result;
}


static void synapse_volume_service_volume_object_real_set_description (SynapseMatch* base, const gchar* value) {
	SynapseVolumeServiceVolumeObject* self;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_description);
	self->priv->_description = _tmp1_;
	g_object_notify ((GObject *) self, "description");
}


static const gchar* synapse_volume_service_volume_object_real_get_icon_name (SynapseMatch* base) {
	const gchar* result;
	SynapseVolumeServiceVolumeObject* self;
	const gchar* _tmp0_ = NULL;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = self->priv->_icon_name;
	result = _tmp0_;
	return result;
}


static void synapse_volume_service_volume_object_real_set_icon_name (SynapseMatch* base, const gchar* value) {
	SynapseVolumeServiceVolumeObject* self;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_icon_name);
	self->priv->_icon_name = _tmp1_;
	g_object_notify ((GObject *) self, "icon-name");
}


static gboolean synapse_volume_service_volume_object_real_get_has_thumbnail (SynapseMatch* base) {
	gboolean result;
	SynapseVolumeServiceVolumeObject* self;
	gboolean _tmp0_ = FALSE;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = self->priv->_has_thumbnail;
	result = _tmp0_;
	return result;
}


static void synapse_volume_service_volume_object_real_set_has_thumbnail (SynapseMatch* base, gboolean value) {
	SynapseVolumeServiceVolumeObject* self;
	gboolean _tmp0_ = FALSE;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = value;
	self->priv->_has_thumbnail = _tmp0_;
	g_object_notify ((GObject *) self, "has-thumbnail");
}


static const gchar* synapse_volume_service_volume_object_real_get_thumbnail_path (SynapseMatch* base) {
	const gchar* result;
	SynapseVolumeServiceVolumeObject* self;
	const gchar* _tmp0_ = NULL;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = self->priv->_thumbnail_path;
	result = _tmp0_;
	return result;
}


static void synapse_volume_service_volume_object_real_set_thumbnail_path (SynapseMatch* base, const gchar* value) {
	SynapseVolumeServiceVolumeObject* self;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_thumbnail_path);
	self->priv->_thumbnail_path = _tmp1_;
	g_object_notify ((GObject *) self, "thumbnail-path");
}


static SynapseMatchType synapse_volume_service_volume_object_real_get_match_type (SynapseMatch* base) {
	SynapseMatchType result;
	SynapseVolumeServiceVolumeObject* self;
	SynapseMatchType _tmp0_ = 0;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = self->priv->_match_type;
	result = _tmp0_;
	return result;
}


static void synapse_volume_service_volume_object_real_set_match_type (SynapseMatch* base, SynapseMatchType value) {
	SynapseVolumeServiceVolumeObject* self;
	SynapseMatchType _tmp0_ = 0;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = value;
	self->priv->_match_type = _tmp0_;
	g_object_notify ((GObject *) self, "match-type");
}


static const gchar* synapse_volume_service_volume_object_real_get_uri (SynapseUriMatch* base) {
	const gchar* result;
	SynapseVolumeServiceVolumeObject* self;
	const gchar* _tmp0_ = NULL;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = self->priv->_uri;
	result = _tmp0_;
	return result;
}


static void synapse_volume_service_volume_object_real_set_uri (SynapseUriMatch* base, const gchar* value) {
	SynapseVolumeServiceVolumeObject* self;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_uri);
	self->priv->_uri = _tmp1_;
	g_object_notify ((GObject *) self, "uri");
}


static SynapseQueryFlags synapse_volume_service_volume_object_real_get_file_type (SynapseUriMatch* base) {
	SynapseQueryFlags result;
	SynapseVolumeServiceVolumeObject* self;
	SynapseQueryFlags _tmp0_ = 0;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = self->priv->_file_type;
	result = _tmp0_;
	return result;
}


static void synapse_volume_service_volume_object_real_set_file_type (SynapseUriMatch* base, SynapseQueryFlags value) {
	SynapseVolumeServiceVolumeObject* self;
	SynapseQueryFlags _tmp0_ = 0;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = value;
	self->priv->_file_type = _tmp0_;
	g_object_notify ((GObject *) self, "file-type");
}


static const gchar* synapse_volume_service_volume_object_real_get_mime_type (SynapseUriMatch* base) {
	const gchar* result;
	SynapseVolumeServiceVolumeObject* self;
	const gchar* _tmp0_ = NULL;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = self->priv->_mime_type;
	result = _tmp0_;
	return result;
}


static void synapse_volume_service_volume_object_real_set_mime_type (SynapseUriMatch* base, const gchar* value) {
	SynapseVolumeServiceVolumeObject* self;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	self = (SynapseVolumeServiceVolumeObject*) base;
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_mime_type);
	self->priv->_mime_type = _tmp1_;
	g_object_notify ((GObject *) self, "mime-type");
}


GVolume* synapse_volume_service_volume_object_get_volume (SynapseVolumeServiceVolumeObject* self) {
	GVolume* result;
	GVolume* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_volume;
	result = _tmp0_;
	return result;
}


static void _synapse_volume_service_volume_object_update_state_g_volume_changed (GVolume* _sender, gpointer self) {
	synapse_volume_service_volume_object_update_state ((SynapseVolumeServiceVolumeObject*) self);
}


void synapse_volume_service_volume_object_set_volume (SynapseVolumeServiceVolumeObject* self, GVolume* value) {
	GVolume* _tmp0_ = NULL;
	GVolume* _tmp1_ = NULL;
	GVolume* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	GVolume* _tmp5_ = NULL;
	GIcon* _tmp6_ = NULL;
	GIcon* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	SynapseMatchType _tmp10_ = 0;
	GVolume* _tmp11_ = NULL;
	GMount* _tmp12_ = NULL;
	GMount* _tmp13_ = NULL;
	gboolean _tmp14_ = FALSE;
	SynapseMatchType _tmp15_ = 0;
	SynapseMatchType _tmp16_ = 0;
	gulong _tmp24_ = 0UL;
	gint _tmp27_ = 0;
	GVolume* _tmp28_ = NULL;
	GMount* _tmp29_ = NULL;
	GMount* _tmp30_ = NULL;
	gboolean _tmp31_ = FALSE;
	const gchar* _tmp32_ = NULL;
	const gchar* _tmp33_ = NULL;
	const gchar* _tmp34_ = NULL;
	const gchar* _tmp35_ = NULL;
	const gchar* _tmp36_ = NULL;
	const gchar* _tmp37_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_volume);
	self->priv->_volume = _tmp1_;
	_tmp2_ = value;
	_tmp3_ = g_volume_get_name (_tmp2_);
	_tmp4_ = _tmp3_;
	synapse_match_set_title ((SynapseMatch*) self, _tmp4_);
	_g_free0 (_tmp4_);
	synapse_match_set_description ((SynapseMatch*) self, "");
	_tmp5_ = value;
	_tmp6_ = g_volume_get_icon (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_icon_to_string (_tmp7_);
	_tmp9_ = _tmp8_;
	synapse_match_set_icon_name ((SynapseMatch*) self, _tmp9_);
	_g_free0 (_tmp9_);
	_g_object_unref0 (_tmp7_);
	synapse_match_set_has_thumbnail ((SynapseMatch*) self, FALSE);
	_tmp11_ = value;
	_tmp12_ = g_volume_get_mount (_tmp11_);
	_tmp13_ = _tmp12_;
	_tmp14_ = _tmp13_ != NULL;
	_g_object_unref0 (_tmp13_);
	if (_tmp14_) {
		_tmp10_ = SYNAPSE_MATCH_TYPE_GENERIC_URI;
	} else {
		_tmp10_ = SYNAPSE_MATCH_TYPE_ACTION;
	}
	synapse_match_set_match_type ((SynapseMatch*) self, _tmp10_);
	_tmp15_ = synapse_match_get_match_type ((SynapseMatch*) self);
	_tmp16_ = _tmp15_;
	if (_tmp16_ == SYNAPSE_MATCH_TYPE_GENERIC_URI) {
		GVolume* _tmp17_ = NULL;
		GMount* _tmp18_ = NULL;
		GMount* _tmp19_ = NULL;
		GFile* _tmp20_ = NULL;
		GFile* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
		gchar* _tmp23_ = NULL;
		_tmp17_ = value;
		_tmp18_ = g_volume_get_mount (_tmp17_);
		_tmp19_ = _tmp18_;
		_tmp20_ = g_mount_get_root (_tmp19_);
		_tmp21_ = _tmp20_;
		_tmp22_ = g_file_get_uri (_tmp21_);
		_tmp23_ = _tmp22_;
		synapse_uri_match_set_uri ((SynapseUriMatch*) self, _tmp23_);
		_g_free0 (_tmp23_);
		_g_object_unref0 (_tmp21_);
		_g_object_unref0 (_tmp19_);
		synapse_uri_match_set_file_type ((SynapseUriMatch*) self, SYNAPSE_QUERY_FLAGS_PLACES);
		synapse_uri_match_set_mime_type ((SynapseUriMatch*) self, "");
	} else {
		synapse_uri_match_set_uri ((SynapseUriMatch*) self, NULL);
	}
	_tmp24_ = self->priv->changed_signal_id;
	if (_tmp24_ == ((gulong) 0)) {
		GVolume* _tmp25_ = NULL;
		gulong _tmp26_ = 0UL;
		_tmp25_ = self->priv->_volume;
		_tmp26_ = g_signal_connect_object (_tmp25_, "changed", (GCallback) _synapse_volume_service_volume_object_update_state_g_volume_changed, self, 0);
		self->priv->changed_signal_id = _tmp26_;
	}
	_tmp28_ = value;
	_tmp29_ = g_volume_get_mount (_tmp28_);
	_tmp30_ = _tmp29_;
	_tmp31_ = _tmp30_ != NULL;
	_g_object_unref0 (_tmp30_);
	if (_tmp31_) {
		_tmp27_ = 1;
	} else {
		_tmp27_ = 0;
	}
	_tmp32_ = synapse_match_get_title ((SynapseMatch*) self);
	_tmp33_ = _tmp32_;
	_tmp34_ = synapse_match_get_icon_name ((SynapseMatch*) self);
	_tmp35_ = _tmp34_;
	_tmp36_ = synapse_uri_match_get_uri ((SynapseUriMatch*) self);
	_tmp37_ = _tmp36_;
	synapse_utils_logger_debug ((GObject*) self, "volume-service.vala:163: vo[%p]: %s [%s], has_mount: %d, uri: %s", self, _tmp33_, _tmp35_, _tmp27_, _tmp37_, NULL);
	g_object_notify ((GObject *) self, "volume");
}


static void synapse_volume_service_volume_object_class_init (SynapseVolumeServiceVolumeObjectClass * klass) {
	synapse_volume_service_volume_object_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SynapseVolumeServiceVolumeObjectPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_synapse_volume_service_volume_object_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_synapse_volume_service_volume_object_set_property;
	G_OBJECT_CLASS (klass)->finalize = synapse_volume_service_volume_object_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_TITLE, g_param_spec_string ("title", "title", "title", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_DESCRIPTION, g_param_spec_string ("description", "description", "description", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_ICON_NAME, g_param_spec_string ("icon-name", "icon-name", "icon-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_HAS_THUMBNAIL, g_param_spec_boolean ("has-thumbnail", "has-thumbnail", "has-thumbnail", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_THUMBNAIL_PATH, g_param_spec_string ("thumbnail-path", "thumbnail-path", "thumbnail-path", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_MATCH_TYPE, g_param_spec_enum ("match-type", "match-type", "match-type", SYNAPSE_TYPE_MATCH_TYPE, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_URI, g_param_spec_string ("uri", "uri", "uri", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_FILE_TYPE, g_param_spec_flags ("file-type", "file-type", "file-type", SYNAPSE_TYPE_QUERY_FLAGS, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_MIME_TYPE, g_param_spec_string ("mime-type", "mime-type", "mime-type", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_VOLUME, g_param_spec_object ("volume", "volume", "volume", g_volume_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void synapse_volume_service_volume_object_synapse_match_interface_init (SynapseMatchIface * iface) {
	synapse_volume_service_volume_object_synapse_match_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_title = synapse_volume_service_volume_object_real_get_title;
	iface->set_title = synapse_volume_service_volume_object_real_set_title;
	iface->get_description = synapse_volume_service_volume_object_real_get_description;
	iface->set_description = synapse_volume_service_volume_object_real_set_description;
	iface->get_icon_name = synapse_volume_service_volume_object_real_get_icon_name;
	iface->set_icon_name = synapse_volume_service_volume_object_real_set_icon_name;
	iface->get_has_thumbnail = synapse_volume_service_volume_object_real_get_has_thumbnail;
	iface->set_has_thumbnail = synapse_volume_service_volume_object_real_set_has_thumbnail;
	iface->get_thumbnail_path = synapse_volume_service_volume_object_real_get_thumbnail_path;
	iface->set_thumbnail_path = synapse_volume_service_volume_object_real_set_thumbnail_path;
	iface->get_match_type = synapse_volume_service_volume_object_real_get_match_type;
	iface->set_match_type = synapse_volume_service_volume_object_real_set_match_type;
}


static void synapse_volume_service_volume_object_synapse_uri_match_interface_init (SynapseUriMatchIface * iface) {
	synapse_volume_service_volume_object_synapse_uri_match_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_uri = synapse_volume_service_volume_object_real_get_uri;
	iface->set_uri = synapse_volume_service_volume_object_real_set_uri;
	iface->get_file_type = synapse_volume_service_volume_object_real_get_file_type;
	iface->set_file_type = synapse_volume_service_volume_object_real_set_file_type;
	iface->get_mime_type = synapse_volume_service_volume_object_real_get_mime_type;
	iface->set_mime_type = synapse_volume_service_volume_object_real_set_mime_type;
}


static void synapse_volume_service_volume_object_instance_init (SynapseVolumeServiceVolumeObject * self) {
	self->priv = SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_GET_PRIVATE (self);
}


static void synapse_volume_service_volume_object_finalize (GObject* obj) {
	SynapseVolumeServiceVolumeObject * self;
	gulong _tmp0_ = 0UL;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObject);
	_tmp0_ = self->priv->changed_signal_id;
	if (_tmp0_ != ((gulong) 0)) {
		GVolume* _tmp1_ = NULL;
		gulong _tmp2_ = 0UL;
		_tmp1_ = self->priv->_volume;
		_tmp2_ = self->priv->changed_signal_id;
		g_signal_handler_disconnect (_tmp1_, _tmp2_);
		self->priv->changed_signal_id = (gulong) 0;
	}
	_g_free0 (self->priv->_title);
	_g_free0 (self->priv->_description);
	_g_free0 (self->priv->_icon_name);
	_g_free0 (self->priv->_thumbnail_path);
	_g_free0 (self->priv->_uri);
	_g_free0 (self->priv->_mime_type);
	_g_object_unref0 (self->priv->_volume);
	G_OBJECT_CLASS (synapse_volume_service_volume_object_parent_class)->finalize (obj);
}


GType synapse_volume_service_volume_object_get_type (void) {
	static volatile gsize synapse_volume_service_volume_object_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_volume_service_volume_object_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseVolumeServiceVolumeObjectClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_volume_service_volume_object_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseVolumeServiceVolumeObject), 0, (GInstanceInitFunc) synapse_volume_service_volume_object_instance_init, NULL };
		static const GInterfaceInfo synapse_match_info = { (GInterfaceInitFunc) synapse_volume_service_volume_object_synapse_match_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo synapse_uri_match_info = { (GInterfaceInitFunc) synapse_volume_service_volume_object_synapse_uri_match_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType synapse_volume_service_volume_object_type_id;
		synapse_volume_service_volume_object_type_id = g_type_register_static (G_TYPE_OBJECT, "SynapseVolumeServiceVolumeObject", &g_define_type_info, 0);
		g_type_add_interface_static (synapse_volume_service_volume_object_type_id, SYNAPSE_TYPE_MATCH, &synapse_match_info);
		g_type_add_interface_static (synapse_volume_service_volume_object_type_id, SYNAPSE_TYPE_URI_MATCH, &synapse_uri_match_info);
		g_once_init_leave (&synapse_volume_service_volume_object_type_id__volatile, synapse_volume_service_volume_object_type_id);
	}
	return synapse_volume_service_volume_object_type_id__volatile;
}


static void _vala_synapse_volume_service_volume_object_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SynapseVolumeServiceVolumeObject * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObject);
	switch (property_id) {
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_TITLE:
		g_value_set_string (value, synapse_match_get_title ((SynapseMatch*) self));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_DESCRIPTION:
		g_value_set_string (value, synapse_match_get_description ((SynapseMatch*) self));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_ICON_NAME:
		g_value_set_string (value, synapse_match_get_icon_name ((SynapseMatch*) self));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_HAS_THUMBNAIL:
		g_value_set_boolean (value, synapse_match_get_has_thumbnail ((SynapseMatch*) self));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_THUMBNAIL_PATH:
		g_value_set_string (value, synapse_match_get_thumbnail_path ((SynapseMatch*) self));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_MATCH_TYPE:
		g_value_set_enum (value, synapse_match_get_match_type ((SynapseMatch*) self));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_URI:
		g_value_set_string (value, synapse_uri_match_get_uri ((SynapseUriMatch*) self));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_FILE_TYPE:
		g_value_set_flags (value, synapse_uri_match_get_file_type ((SynapseUriMatch*) self));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_MIME_TYPE:
		g_value_set_string (value, synapse_uri_match_get_mime_type ((SynapseUriMatch*) self));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_VOLUME:
		g_value_set_object (value, synapse_volume_service_volume_object_get_volume (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_synapse_volume_service_volume_object_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SynapseVolumeServiceVolumeObject * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SYNAPSE_VOLUME_SERVICE_TYPE_VOLUME_OBJECT, SynapseVolumeServiceVolumeObject);
	switch (property_id) {
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_TITLE:
		synapse_match_set_title ((SynapseMatch*) self, g_value_get_string (value));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_DESCRIPTION:
		synapse_match_set_description ((SynapseMatch*) self, g_value_get_string (value));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_ICON_NAME:
		synapse_match_set_icon_name ((SynapseMatch*) self, g_value_get_string (value));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_HAS_THUMBNAIL:
		synapse_match_set_has_thumbnail ((SynapseMatch*) self, g_value_get_boolean (value));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_THUMBNAIL_PATH:
		synapse_match_set_thumbnail_path ((SynapseMatch*) self, g_value_get_string (value));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_MATCH_TYPE:
		synapse_match_set_match_type ((SynapseMatch*) self, g_value_get_enum (value));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_URI:
		synapse_uri_match_set_uri ((SynapseUriMatch*) self, g_value_get_string (value));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_FILE_TYPE:
		synapse_uri_match_set_file_type ((SynapseUriMatch*) self, g_value_get_flags (value));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_MIME_TYPE:
		synapse_uri_match_set_mime_type ((SynapseUriMatch*) self, g_value_get_string (value));
		break;
		case SYNAPSE_VOLUME_SERVICE_VOLUME_OBJECT_VOLUME:
		synapse_volume_service_volume_object_set_volume (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void synapse_volume_service_class_init (SynapseVolumeServiceClass * klass) {
	synapse_volume_service_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SynapseVolumeServicePrivate));
	G_OBJECT_CLASS (klass)->constructor = synapse_volume_service_constructor;
	G_OBJECT_CLASS (klass)->finalize = synapse_volume_service_finalize;
}


static void synapse_volume_service_instance_init (SynapseVolumeService * self) {
	self->priv = SYNAPSE_VOLUME_SERVICE_GET_PRIVATE (self);
}


static void synapse_volume_service_finalize (GObject* obj) {
	SynapseVolumeService * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SYNAPSE_TYPE_VOLUME_SERVICE, SynapseVolumeService);
	synapse_volume_service_instance = NULL;
	_g_object_unref0 (self->priv->vm);
	_g_object_unref0 (self->priv->volumes);
	G_OBJECT_CLASS (synapse_volume_service_parent_class)->finalize (obj);
}


GType synapse_volume_service_get_type (void) {
	static volatile gsize synapse_volume_service_type_id__volatile = 0;
	if (g_once_init_enter (&synapse_volume_service_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SynapseVolumeServiceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) synapse_volume_service_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SynapseVolumeService), 0, (GInstanceInitFunc) synapse_volume_service_instance_init, NULL };
		GType synapse_volume_service_type_id;
		synapse_volume_service_type_id = g_type_register_static (G_TYPE_OBJECT, "SynapseVolumeService", &g_define_type_info, 0);
		g_once_init_leave (&synapse_volume_service_type_id__volatile, synapse_volume_service_type_id);
	}
	return synapse_volume_service_type_id__volatile;
}



